### ISSUE TITLE
ownCloud CalDAV problem

### ISSUE THREAD

**Issue by chspnk** [gggard/AndroidCaldavSyncAdapater#10]
First I tried to connect to my owncloud CalDAV per https-Proxy and it says the same as the other guy (I dont remember the name) said: "Invalid server answer, check URL"
Second i tried to connect per http and it says: "This password is incorrect" But I am sure it is!
If you tell me how to give details I will do.. :)

**Comment by gggard** [comment]
Thanks for the report, I am marking your issue as duplicate from #9 
If solving #9  does not solve your problem, do not hesitate to re-open it
