### ISSUE TITLE
Cannot sync with 1.8 alpha 2

### ISSUE THREAD

**Issue by spineaker** [gggard/AndroidCaldavSyncAdapater#100]
I Tried the unofficial rev. 1.8 Alpha-2.
I can't connect to the caldav server using : 
- ownCloud 5.0.10
- ssl with self signed certificate

The error is : "the provider failed to get an existing or create a new calendar"

I have the same error with the two links proposed by owncloud :
../remote.php/caldav/
and
../remote.php/caldav/principals/user/

PS : i didn't found how to report the issue to timoberger's branch.

**Comment by timoberger** [comment]
that was fast.
could you describe your mistake please? (to understand the users problems better and to make documentation understandable)

**Comment by spineaker** [comment]
My mistake was to close the issue, sorry. :)

**Comment by timoberger** [comment]
are you using the cyanogenmod with privacy extension?

**Comment by spineaker** [comment]
Exactly, that was the problem, the app was blocked by this extension.
Everything seems to work (2 ways syncing).

Now I can close the issue!

Thank you for all the work done.
