### ISSUE TITLE
Sync with owncloud only gives 'all day' events.

### ISSUE THREAD

**Issue by DjSlash** [gggard/AndroidCaldavSyncAdapater#104]
Owncloud: 5.0.11
ACSA: 1.7 (via f-droid)
Android: 4.1.2 (HTC Sence 4+)

Added an account, synced and all events seemed synced correctly, except for that they are all set as 'all day' events.

**Comment by timoberger** [comment]
this is a know bug in v1.7
you can try my pre-release v1.8-alpha-3
https://github.com/timoberger/AndroidCaldavSyncAdapater/releases/tag/V1.8-alpha-3

**Comment by timoberger** [comment]
feel free to reopen when needed
