### ISSUE TITLE
incomplete radicale support

### ISSUE THREAD

**Issue by leaf-node** [gggard/AndroidCaldavSyncAdapater#107]
i use the [radicale](http://radicale.org) caldav server.

using version 5dc78b20604db7746ae5d859396cb554e8471c5f with pull request #83 merged in, calendars are slow to be discovered, and only one event shows up per month for the last three months.

using 5dc78b20604db7746ae5d859396cb554e8471c5f without the pull request (and after deleting the old account, then making a new one) only one calendar was discovered, syncing keeps progressing, and no events show up.

i'm really excited for this project, so thanks for the contribution! :-)

**Comment by timoberger** [comment]
i am not sure about what acually happend and what should have happend.

can you describe the issue in more details please?

**Comment by leaf-node** [comment]
i added a caldav sync adapter account connected to a radicale caldav server running on a vps of mine. i get a message saying that it was successfully added, and then i go to the calendars view, and see that no calendars are found yet. but then in a few seconds of navigating around menus, i see one calendar show up in the list. then maybe 30 seconds later (or even much later), i see the other calendar for that account show up in the available calendars list.

one of the times i tried this, i saw three calendar events show up. each event was for a different month. another time, no events showed up. after being first added, the account detail in the system preferences shows that it is syncing for a long time.

what i expected was for both calendars to appear when the first calendar appears, or within a few seconds. i also expected all of my events to show up, since i have more than 3 events on my calendars.

as for the original bug report, eventually all calendars showed up. also, i don't think that i actually merged in the ssl patch anyhow ( #83 ). i am using a cyanogenmod 10.2 nightly on the i9100 (galaxy s2) and am mostly pleased with its stability.

thanks! :-)

**Comment by timoberger** [comment]
can you create a network dump with Charles Proxy (http://www.charlesproxy.com/) while you are adding a new account? i would like to see what is going on there. send the dump directly to me: timoberger@users.sourceforge.net
the debug output would be helpful too.
do you have many events in your calendars? this could explain why the calendars are added slowly.
if i understood you right, there are very few events synchronized?

**Comment by timoberger** [comment]
@sudoman did you check the latest release?

**Comment by leaf-node** [comment]
i did try out the latest version, and i remember it being better. calendar discovery was still slow to find the second calendar, and few or no events showed up.

as for the data you're looking for, are you looking for unencrypted packets? i'm a little hesitant to use http... i think charlesproxy is non-free, so would wireshark data be of use?

**Comment by timoberger** [comment]
wireshark would also be fine. please send any dump directly to me (no this list).
i suggest people to use charles because it is easier to install.

**Comment by timoberger** [comment]
i promise not to make use of any data that were send to me for debugging the sync adapter.

**Comment by timoberger** [comment]
@sudoman i would like to close this issue, because radicale is basically supported and i want to publish V1.8 in some days.
you should describe your current issue (second calendar not syncing?) in more detail in another issue. i.e. i don't see an option within radicale to create a second calendar for a user. i would like to do this also.
