### ISSUE TITLE
timoberger/AndroidCaldavSyncAdapater alpha-4

### ISSUE THREAD

**Issue by AdamN1** [gggard/AndroidCaldavSyncAdapater#109]
Hello,
## i just installed version alpha-4 and with this release i can't sync with davical. Below error from davical

davical: LOG: request:Request is "REPORT" but client set content-type to "text/xml;charset="UTF-8"". Assuming they meant XML!
davical: LOG: request:Request is "REPORT" but client set content-type to "text/xml;charset="UTF-8"". Assuming they meant XML!
davical: LOG: request:Request is "REPORT" but client set content-type to "text/xml;charset="UTF-8"". Assuming they meant XML!
davical: LOG: request:Request is "PROPFIND" but client set content-type to "application/xml;charset="UTF-8"". Assuming they meant XML!
davical: LOG: request:Request is "REPORT" but client set content-type to "text/xml;charset="UTF-8"". Assuming they meant XML!
davical: LOG: request:Request is "REPORT" but client set content-type to "text/xml;charset="UTF-8"". Assuming they meant XML!
davical: LOG: request:Request is "REPORT" but client set content-type to "text/xml;charset="UTF-8"". Assuming they meant XML!
davical: LOG: request:Request is "PROPFIND" but client set content-type to "application/xml;charset="UTF-8"". Assuming they meant XML!
davical: LOG: request:Request is "REPORT" but client set content-type to "text/xml;charset="UTF-8"". Assuming they meant XML!

---

**Comment by timoberger** [comment]
taken from CaldavFacade (create REPORT Request):
Line 634:       //request.setHeader("Content-Type", "application/xml;charset=\"UTF-8\"");
Line 635:       request.setHeader("Content-Type", "text/xml;charset=\"UTF-8\"");

but why did i change the content-type to text/xml?

**Comment by timoberger** [comment]
as far as i am reading davical, this error should not lead to an error.
when you say "i can't sync with davical", what does that mean in detail?
what does happen and what is not happening?

**Comment by AdamN1** [comment]
The client does not return any error. Unfortunately, there are also no entries retrieved from the davical server.

**Comment by timoberger** [comment]
this could be issue #107 
i release alpha-5.
could you please test this version?

**Comment by AdamN1** [comment]
installed versions alpha-5, unfortunately, no change. how can I help you locate the problem?

**Comment by timoberger** [comment]
can you create a network dump with charles proxy? http://www.charlesproxy.com/
please send the dump to timoberger@users.sourceforge.net

even easier would be a test account for me.

**Comment by AdamN1** [comment]
test account
login: test
pass: qazxcdews
address: https://www.example.com/caldav.php/test/
edited by timoberger

**Comment by timoberger** [comment]
there is a bug in alpha-5 that prevents the adapter from reading events in a calendar.

but: your davical acts some kind of strange. the returned ctag for the calendar test/calendar is always -1. it doesn't get changed.

``` xml
<?xml version="1.0" encoding="utf-8" ?>
<multistatus xmlns="DAV:" xmlns:C="urn:ietf:params:xml:ns:caldav" xmlns:C1="http://calendarserver.org/ns/" xmlns:A="http://apple.com/ns/ical/">
    <response>
        <href>/caldav.php/test/calendar/</href>
        <propstat>
            <prop>
                <displayname>Uzytkownik Testowy calendar</displayname>
                <resourcetype>
                    <collection/>
                    <C:calendar/>
                </resourcetype>
                <C1:getctag>"-1"</C1:getctag>
            </prop>
            <status>HTTP/1.1 200 OK</status>
        </propstat>
        <propstat>
            <prop>
                <A:calendar-color/>
            </prop>
            <status>HTTP/1.1 404 Not Found</status>
        </propstat>
    </response>
```

**Comment by timoberger** [comment]
an unchanged ctag lets the adapter think, that there are no changes within the calender, even if an event has been changed.

**Comment by timoberger** [comment]
basically the initial sync sends you all events in your calendar. but changes made on server side will never hit your client.

**Comment by AdamN1** [comment]
about the ctag, this is bug in davical or wrong configuration?

**Comment by timoberger** [comment]
this could be a problem on your side. i searched for this behavior of davical but found ctags with a "regular" value only. see i. e. http://forum.myroundcube.com/#nabble-td4024675

``` xml
<?xml version="1.0" encoding="utf-8" ?>
<multistatus xmlns="DAV:" xmlns:C="http://calendarserver.org/ns/" xmlns:C1="urn:ietf:params:xml:ns:caldav">
    <response>
        <href>/davical/caldav.php/Felix/calendar/</href>
        <propstat>
            <prop>
                <displayname>BrasilPrivat</displayname>
                <C:getctag>"e7d4640c80df851f6830f6e82baa635a"</C:getctag>
                <resourcetype>
                    <collection/>
                    <C1:calendar/>
                </resourcetype>
            </prop>
            <status>HTTP/1.1 200 OK</status>
        </propstat>
    </response>
```

maybe you are using a faulty version or 
your db has some errors and doesn't update the ctag or
i am not a davical developer. sorry.

**Comment by timoberger** [comment]
i tried to install davical by myself and ended up with the create-database.sh not creating a proper db without errors.
i will give it a second try but not for today.

**Comment by AdamN1** [comment]
searching davical code i found

```
public function unique_tag() {
    if ( isset($this->unique_tag) ) return $this->unique_tag;

    if ( $this->exists !== true ) $this->unique_tag = '"-1"';

    return $this->unique_tag;
}
```

**Comment by timoberger** [comment]
the response of your server clearly says that getctag is valid for the reference

``` xml
        <propstat>
            <prop>
                <displayname>Uzytkownik Testowy calendar</displayname>
                <resourcetype>
                    <collection/>
                    <C:calendar/>
                </resourcetype>
                <C1:getctag>"-1"</C1:getctag>
            </prop>
            <status>HTTP/1.1 200 OK</status>
        </propstat>
```

i. e. the calendar-color is not valid for the reference

``` xml
        <propstat>
            <prop>
                <A:calendar-color/>
            </prop>
            <status>HTTP/1.1 404 Not Found</status>
        </propstat>
```

i could be wrong and the ctag -1 states something else (maybe look somewhere else). if so, i have no idea how to handle this.

**Comment by AdamN1** [comment]
Do I understand correctly you think that CTAG means "color tag" for calendar?

from the davical (code + description)

```
  /**
  * Returns the unique_tag (ETag or getctag) for this resource
  */
  public function unique_tag() {
    if ( isset($this->unique_tag) ) return $this->unique_tag;

    if ( $this->exists !== true ) $this->unique_tag = '"-1"';

    return $this->unique_tag;
  }
```

and 

```
  /**
   * A unique tag which will change if this principal changes
   * @var string
   */
  private $unique_tag;
```

I think davical uses "CTAG" for the version of the entry.

**Comment by timoberger** [comment]
the CTAG (Calendar TAG) describe an unique TAG for the calendar.
there is also the ETAG (Event TAG) which desrcibes an unique TAG for an event.

if you change an event, the ETAG and the CTAG are both updated. this idicates to a client that something has change within the event or calendar.
if the calendar always sends -1, the client has no chance to see that there was a change.

**Comment by AdamN1** [comment]
In the previous ticket attach tshark log that shows that CTAG is not empty.
What test can i do to check this?

**Comment by timoberger** [comment]
you mistake something
for the reference /caldav.php/test/ the ctag is "093e06a0894f850946de450e001d6831" (this is not the calendar)
for the reference /caldav.php/test/calendar/ the ctag is "-1" (this is the calendar)

``` xml
    <multistatus
        xmlns="DAV:"
        xmlns:C="http://calendarserver.org/ns/"
        xmlns:C1="urn:ietf:params:xml:ns:caldav"
        xmlns:C2="urn:ietf:params:xml:ns:carddav">
        <response>
            <href>
                /caldav.php/test/
                </href>
            <propstat>
                <prop>
                    <displayname>
                        U\305\274ytkownik Testowy
                        </displayname>
                    <resourcetype>
                        <collection/>
                        <principal/>
                        </resourcetype>
                    <C:getctag>
                        "093e06a0894f850946de450e001d6831"
                        </C:getctag>
                    </prop>
                <status>
                    HTTP/1.1 200 OK
                    </status>
                </propstat>
            </response>
        <response>
            <href>
                /caldav.php/test/calendar/
                </href>
            <propstat>
                <prop>
                    <displayname>
                        U\305\274ytkownik Testowy calendar
                        </displayname>
                    <resourcetype>
                        <collection/>
                        <C1:calendar/>
                        </resourcetype>
                    <C:getctag>
                        "-1"
                        </C:getctag>
                    </prop>
                <status>
                    HTTP/1.1 200 OK
                    </status>
                </propstat>
```

**Comment by timoberger** [comment]
this is the output of my davical instance
as you can see for the reference /caldav.php/username/ the CTAG is "105cdaee8b29a87e35e955e38fc632ad"
and for the reference /caldav.php/username/calendar/ the CTAG is "e6da5734431adb459f70db2accea40e4"

tested with davical version 1.1.1-2 with libawl-php 0.53-1, fresh installation.

``` xml
<?xml version="1.0" encoding="utf-8" ?>
<multistatus xmlns="DAV:" xmlns:C="http://calendarserver.org/ns/" xmlns:A="http://apple.com/ns/ical/" xmlns:C1="urn:ietf:params:xml:ns:caldav" xmlns:C2="urn:ietf:params:xml:ns:carddav">
    <response>
        <href>/caldav.php/username/</href>
        <propstat>
            <prop>
                <displayname>my name</displayname>
                <resourcetype>
                    <collection/>
                    <principal/>
                </resourcetype>
                <C:getctag>"105cdaee8b29a87e35e955e38fc632ad"</C:getctag>
            </prop>
            <status>HTTP/1.1 200 OK</status>
        </propstat>
        <propstat>
            <prop>
                <A:calendar-color/>
            </prop>
            <status>HTTP/1.1 404 Not Found</status>
        </propstat>
    </response>
    <response>
        <href>/caldav.php/username/calendar/</href>
        <propstat>
            <prop>
                <displayname>my name calendar</displayname>
                <resourcetype>
                    <collection/>
                    <C1:calendar/>
                </resourcetype>
                <C:getctag>"e6da5734431adb459f70db2accea40e4"</C:getctag>
            </prop>
            <status>HTTP/1.1 200 OK</status>
        </propstat>
        <propstat>
            <prop>
                <A:calendar-color/>
            </prop>
            <status>HTTP/1.1 404 Not Found</status>
        </propstat>
    </response>
```

your installation is faulty

**Comment by AdamN1** [comment]
I asked the developers about the CTAG, the reply

```
Better not to use ctag at all.
It is a non-standard Apple extension which is superseded by the sync-token
```

where you found the version 1.1.1-2?

**Comment by timoberger** [comment]
Evert Pot (developer of SabreDAV) created a tutorial for creating CalDAV clients [1]: "Every calendar has a so-called 'ctag'. This ctag works like a change id. Every time the ctag has changed, you know something in the calendar has changed too. "
Is there a thread at davical?

source of my version: [2]
[1] http://code.google.com/p/sabredav/wiki/BuildingACalDAVClient
[2] http://debian.mcmillan.net.nz/packages/davical/

**Comment by AdamN1** [comment]
I changed versions, you can check?
about your question i will ask

**Comment by timoberger** [comment]
still the same response

``` xml
<?xml version="1.0" encoding="utf-8" ?>
<multistatus xmlns="DAV:" xmlns:C="http://calendarserver.org/ns/" xmlns:A="http://apple.com/ns/ical/" xmlns:C1="urn:ietf:params:xml:ns:caldav" xmlns:C2="urn:ietf:params:xml:ns:carddav">
    <response>
        <href>/caldav.php/test/</href>
        <propstat>
            <prop>
                <displayname>Uzytkownik Testowy</displayname>
                <resourcetype>
                    <collection/>
                    <principal/>
                </resourcetype>
                <C:getctag>"6a9b6f63558e382d5a2322bb7641ae93"</C:getctag>
            </prop>
            <status>HTTP/1.1 200 OK</status>
        </propstat>
        <propstat>
            <prop>
                <A:calendar-color/>
            </prop>
            <status>HTTP/1.1 404 Not Found</status>
        </propstat>
    </response>
    <response>
        <href>/caldav.php/test/calendar/</href>
        <propstat>
            <prop>
                <displayname>Uzytkownik Testowy calendar</displayname>
                <resourcetype>
                    <collection/>
                    <C1:calendar/>
                </resourcetype> 
                <C:getctag>"-1"</C:getctag>
            </prop>
            <status>HTTP/1.1 200 OK</status>
        </propstat>
        <propstat>
            <prop>
                <A:calendar-color/>
            </prop>
            <status>HTTP/1.1 404 Not Found</status>
        </propstat>
    </response>
```

**Comment by karora** [comment]
regression=# \d caldav_data

.....

Triggers:
    caldav_data_modified AFTER INSERT OR DELETE OR UPDATE ON caldav_data FOR EACH ROW EXECUTE PROCEDURE caldav_data_modified()
    caldav_data_sync_dav_id AFTER INSERT OR UPDATE ON caldav_data FOR EACH ROW EXECUTE PROCEDURE sync_dav_id()

Sounds like your database might be missing those triggers.

Cheers,
Andrew

**Comment by AdamN1** [comment]
i have re-added trigger

**Comment by timoberger** [comment]
congrats, your server sends a valid ctag. i will publish a new alpha-release for the bug mentioned above (there is a bug in alpha-5 that prevents the adapter from reading events in a calendar.)
@karora thanks a lot

``` xml
<?xml version="1.0" encoding="utf-8" ?>
<multistatus xmlns="DAV:" xmlns:C="http://calendarserver.org/ns/" xmlns:A="http://apple.com/ns/ical/" xmlns:C1="urn:ietf:params:xml:ns:caldav" xmlns:C2="urn:ietf:params:xml:ns:carddav">
    <response>
        <href>/caldav.php/test/</href>
        <propstat>
            <prop>
                <displayname>Uzytkownik Testowy</displayname>
                <resourcetype>
                    <collection/>
                    <principal/>
                </resourcetype>
                <C:getctag>"6a9b6f63558e382d5a2322bb7641ae93"</C:getctag>
            </prop>
            <status>HTTP/1.1 200 OK</status>
        </propstat>
        <propstat>
            <prop>
                <A:calendar-color/>
            </prop>
            <status>HTTP/1.1 404 Not Found</status>
        </propstat>
    </response>
    <response>
        <href>/caldav.php/test/calendar/</href>
        <propstat>
            <prop>
                <displayname>Uzytkownik Testowy calendar</displayname>
                <resourcetype>
                    <collection/>
                    <C1:calendar/>
                </resourcetype>
                <C:getctag>"827df9ac03705eb8dcbf5de0e71f80d5"</C:getctag>
            </prop>
            <status>HTTP/1.1 200 OK</status>
        </propstat>
        <propstat>
            <prop>
                <A:calendar-color/>
            </prop>
            <status>HTTP/1.1 404 Not Found</status>
        </propstat>
    </response>
```

**Comment by karora** [comment]
Just as an aside, you should consider whether you can make use of DAV::sync-token rather than the Apple Calendarserver 'CTag' extension.  See RFC 6578 for full details.

**Comment by timoberger** [comment]
thanks for the suggestion. i am going to drag this into consideration for a future release.
the ctag has to be good for now.

**Comment by timoberger** [comment]
@AdamN1 i just release the alpha-6 with the changes for davical.
please test the version and send us a report.

**Comment by AdamN1** [comment]
Just installed, so far tested:
first synchronization - works
synchronization from caldav - works
adding new entries from android - works
what else can i check ?
Can you tell what at this time does not work?

I do not see one option "how often to sync"

**Comment by timoberger** [comment]
all implemented function should work now. no further know bugs do exist.
there is no option for the synchronization interval. android is triggering the sync adapter.

**Comment by timoberger** [comment]
i think this can be closed.
feel free to reopen if needed.
