### ISSUE TITLE
I can't find version 1.8 on F-Droid

### ISSUE THREAD

**Issue by LudovicRousseau** [gggard/AndroidCaldavSyncAdapater#113]
The latest version available at F-Droid is 1.7
https://f-droid.org/repository/browse/?fdfilter=caldav&fdid=org.gege.caldavsyncadapter

The wiki page talks about version 1.8 with 2 way sync
https://github.com/gggard/AndroidCaldavSyncAdapater/wiki/Installation-and-configuration

Is this 1.8 version already available/stable/released?

**Comment by LudovicRousseau** [comment]
Since 2 way sync is not yet ready (see https://github.com/gggard/AndroidCaldavSyncAdapater/issues/86) I guess version 1.8 is not yet published.

Exact?

**Comment by timoberger** [comment]
i am planning to release v1.8 on 2013-10-01. but i am not sure if this will be deployed at google play store.
you can test my pre-release of the v1.8 here https://github.com/timoberger/AndroidCaldavSyncAdapater/releases

**Comment by LudovicRousseau** [comment]
I tried V1.8-alpha-5 and synchronisation do not work even from the server to the phone.
v1.7 worked. I use a DAViCal server.
How can I help?

**Comment by timoberger** [comment]
the issue with davical has been handled with issue #109 
i just updated my latest release to fix this.
please test my alpha-6 and send us a report please.

**Comment by LudovicRousseau** [comment]
Exact. The alpha-6 can do the 1 way sync (updates on the server are seen on the phone).
And the 2 way sync also works (at least in the simple tests I made).
Thanks
