### ISSUE TITLE
Request is "REPORT" but client set content-type to "application/xml;charset="UTF-8"". Assuming they meant XML!

### ISSUE THREAD

**Issue by LudovicRousseau** [gggard/AndroidCaldavSyncAdapater#114]
For this request (from `ssl_access.log`):

freebox - rousseau [27/Sep/2013:15:08:23 +0200] "REPORT /davical/caldav.php HTTP/1.1" 207 623 "-" "CalDAV Sync Adapter (Android) https://github.com/gggard/AndroidCaldavSyncAdapater Version:1.8-alpha-5"

My DAViCal server reports this error (from `error.log`):

[Fri Sep 27 15:08:23 2013] [error] [client 192.168.0.254] davical: LOG: request:Request is "REPORT" but client set content-type to "application/xml;charset="UTF-8"". Assuming they meant XML!

**Comment by timoberger** [comment]
this is not a bug, it is a feature.
this message doesn't lead to an error.
