### ISSUE TITLE
Connexion impossible

### ISSUE THREAD

**Issue by jiremek** [gggard/AndroidCaldavSyncAdapater#12]
Le mot de passe ne fonctionne pas.
Il fonctionne pourtant parfaitement sous Thunderbird avec le plugin Lightning.

Version 1.3

**Comment by chspnk** [comment]
C'est la meme pour moi, je pense que c'est en relation avec issue #9 ou #10

**Comment by minami-o** [comment]
@jiremek : Il serait sans doute utile au développeur d'ajouter des précisions, comme le type de serveur ou le site web de connexion, le message d'erreur s'il y en a un, etc.

**Comment by jiremek** [comment]
Ce n'est pas faut.
Il s'agit d'un DaviCal.
Le mot de passe ne comporte pas de caractères spéciaux.
L’accès ce fait en http
Pour le message "This password is incorrect" soit "Ce mot de passe est incorrecte".

**Comment by chspnk** [comment]
Comme je te l'ai deja dit: C'est une probleme connue...
Attend la response du developpeur!

**Comment by jiremek** [comment]
En fait je ne pense pas que cela doit lié, d'abord parce que je n'utilise pas de proxy, ensuite la version précédente se connecter mais planté a la synchronisation.

**Comment by gggard** [comment]
Bonsoir,
C'est du http ou https ?

**Comment by jiremek** [comment]
En http comme indiqué.
Il s'agit d'un service auto-hebergé, ne comportant pas de spécificités.

**Comment by minami-o** [comment]
Excellent work! I could sync and find all my Baikal calendars in Google Agenda!
Many thanks for your quick action!
Now all I need is the possibility to change events from the client - can't wait for you to implement this enhancement! :D

Edit: sorry, mixed threads - issue #6 is solved

**Comment by gggard** [comment]
Thanks for the feedback, that's a good news

For the sync from android to server, I wait some weeks in order to be 
sure that there is no bug in the other way,
in case of problem, the app could decide to drop all the events on the 
server... :-(

**Comment by jiremek** [comment]
Password work, but not sync

**Comment by gggard** [comment]
jiremek : could you give me more details on your issue ?
As it seams to work for some user, please could you open a new issue with your problem, it will help the tracking...

**Comment by jiremek** [comment]
Sync not worked 'cause of crash. #15
