### ISSUE TITLE
Meetings created in in different time zone than your home zone do not get translated to the correct time.

### ISSUE THREAD

**Issue by kedarbhise** [gggard/AndroidCaldavSyncAdapater#122]
Using the free version with Zimbra Server at the backend. Used the URL as mentioned on this page:
https://github.com/gggard/AndroidCaldavSyncAdapater/wiki
The URL worked fine for sync. All my events on the server show up on the handset.
When I receive an invite from other timezones, Zimbra handles them correctly and translates to my timezone. When the sync happens, I see the event with the start time numerically the same, but in my time zone.
An example:
I am in India - GMT +05:30
I receive an invitation for UK time 09:00.
Zimbra shows it correctly on my server calendar as 13:30 India (with Daylight Savings and all)
Thunderbird syncs with the server calendar and shows it correctly at 13:30
My phone pulls in the event, and shows it as 09:00 India.
Let me know if you need more information.

**Comment by timoberger** [comment]
which version are you using?

**Comment by kedarbhise** [comment]
I saw this issue on v1.7. Have updated to v1.8 today, 28 Oct. Will observe for a couple of days and update here.

**Comment by timoberger** [comment]
i will close this issue.
feel free to reopen if needed.
