### ISSUE TITLE
1.8 available on GooglePlay

### ISSUE THREAD

**Issue by fancarpedia** [gggard/AndroidCaldavSyncAdapater#124]
(When) Will be 1.8 version available on GoolgePlay?

**Comment by vlapla** [comment]
Maybe you already knew this, or it is not what you're looking for, but 1.8 is already available on
https://f-droid.org/ . I prefer F-Droid over Play anyway, because all applications there are free "as in freedom" (and you get OsmAnd+ for free, too).

**Comment by fancarpedia** [comment]
Yeah, I downloaded is directly from github, but for people without 
computer skills (means my family, some friends etc) is yeasier to tell them,
download it from google play as gofload f-droid, then find it there and 
than install.

Anyway, if there is 1.7 it can be easy to switch package (or not?)

**Comment by timoberger** [comment]
Gérald (gggard) is the owner of the google account where the sync adapter has been released. I was hoping that he would release a new version at google play.

**Comment by fancarpedia** [comment]
Understand. Is it possible to contact them with this request? Or can he give you a permission to doit?

**Comment by timoberger** [comment]
I am not sure about this. I do not have a regular google account so i don't know whether this is possible.

**Comment by fancarpedia** [comment]
OK. So it seams, that we will wait for reaction of Gérald about it ;-(

**Comment by gggard** [comment]
Sorry I deduce that I miss the green light from you ! 
Two solutions I give you access to play dashboard (need your gmail mail), either give me he apk and I will upload it (I can write a short release note but if you want to do this do not hesitate)
Sorry

timoberger notifications@github.com a écrit :

**Comment by timoberger** [comment]
@stanolacko the version 1.8 is now available at googles play store

**Comment by fancarpedia** [comment]
Great, thank you.

Stano
