### ISSUE TITLE
http-header "host" ignores the server port

### ISSUE THREAD

**Issue by timoberger** [gggard/AndroidCaldavSyncAdapater#126]
the http-heder "host" is being set only with the server name. the port is missing.

**Comment by timoberger** [comment]
@djbarry please tell me the correct name and version of the server.
is it apples "caldavd" from ubuntu?

**Comment by djbarry** [comment]
Debian (the mother ship from which Ubuntu poaches), caldavd (package name calendarserver) version 3.2.  Although it's not the most enterprise-featured implementation, Apple regards it as a "reference implementation" against which to test their own caldav/carddav protocols, so it's a good implementation to test against.

Many thanks for your industrious work on this important free software project.

**Comment by djbarry** [comment]
I can confirm that your commit solved my problem.  Thanks!

**Comment by timoberger** [comment]
thanks
