### ISSUE TITLE
Sync with ownCloud 5.0.12 server

### ISSUE THREAD

**Issue by shrkz** [gggard/AndroidCaldavSyncAdapater#127]
Hi
I was testing the sync with Android 4.0.2 and ownCloud 5.0.12. The events from the server are synchronized to Android calendar but as "whole day events".
Furthermore, events created in Android are NOT synchronized to the ownCloud server.

Please contact me if you need additional information.

Thanks.

**Comment by timoberger** [comment]
which version are you using?

**Comment by shrkz** [comment]
The newest from play store today - I guess 1.8 .

**Comment by timoberger** [comment]
the play store has the version 1.7 which has no 2way sync. sorry.
