### ISSUE TITLE
2-way sync

### ISSUE THREAD

**Issue by safisher** [gggard/AndroidCaldavSyncAdapater#128]
The CalDav Sync Adapter appears to correctly pull my events from my ownCloud install (via https). However it doesn't upload any changes to the server. I also use 
"CardDAV-Sync free beta" which does correctly save CardDav changes to the server. So it appears like a CalDav specific problem. I'm using Android 4.3.

**Comment by timoberger** [comment]
Hello,

Are you using the version from google play? This version doesn't support 2way sync at the moment.
I updated the release text (referring to the version 1.8) within google play but wasn't able to update the apk-file. Sorry.

**Comment by safisher** [comment]
Yup, that would be the problem.

Thanks!
