### ISSUE TITLE
Not available with android < 4.0

### ISSUE THREAD

**Issue by roidelapluie** [gggard/AndroidCaldavSyncAdapater#13]
Hello

You application should be available for android < 4.0 (e.g gingerbread).

Thanks.

**Comment by gggard** [comment]
Your right, the problem is that the calendard API apprear only in >4.0 I think.
Let put this as an enhancement request, I will look at it.

**Comment by albialbi** [comment]
Yes please add 2.3 support. Would great.

Thanks for the app!

**Comment by jiremek** [comment]
add support for 2.3 to 4.0 know that ggard need to rewrite all and port the calendar api
But old android device part of in use is decrease

**Comment by albialbi** [comment]
Ok, looks like I have to upgrade to Androd 4. Hope can do it.

**Comment by dschuermann** [comment]
H ggard,
I have made a backward compatibility version of CalendarContract: https://github.com/dschuermann/android-calendar-compatibility
But you really need to test everything on Android < 4. Some things need extra care.

**Comment by gggard** [comment]
Thanks Dominik, that's nice, I will get a try on that and see if it is working.
I am afraid I will have to publish then two different apps in order to not mix your API and the ICS one...

**Comment by dschuermann** [comment]
Oh no, you don't have to. This is the ICS CalendarContract class. Look at it, there is a switch returning different values based on the android version it is running on.

I used it for example in my app Birthday Adapter, which is compatible from 2.2 until the newest 4.2: https://github.com/dschuermann/birthday-adapter

**Comment by kaazoo** [comment]
I'm using Android 2.3.7 on HTC Desire and would like to use AndroidCaldavSyncAdapater together with ownCloud. Would be really nice if you could add dschuermann's compatibility class!

**Comment by logomancer** [comment]
In the efforts of moving things along with this, I attempted to implement Dominik's CalendarContract class by making a new android.provider package and importing the source file into the project. After changing the manifest so it works with API 10 (Gingerbread), it installs, and you can add a sync account and sign in, but the calendars don't show up in either the calendar application or the sync adapter account listing. It just keeps showing the syncing notification in the status bar. A logcat shows that the adapter is retrieving the remote calendars; it just isn't importing them into the local calendar store.

It appears that this isn't a trivial thing on the surface. I want to help, but I'm not sure exactly where to start with this. Any help would be appreciated.

**Comment by timoberger** [comment]
as time goes by, the most pre 4.0 devices will disappear.
the amount of work to be done for this enhancement is far too high. when this goal would be reached, there could be no one in need of it.

just my opinion

**Comment by christianix** [comment]
Hi Logomancer, could you share the changes you made? I'm new to Android but with quite a bit Java experience. Maybe I can help out.
