### ISSUE TITLE
NullPointerException at Parsing

### ISSUE THREAD

**Issue by Merdica** [gggard/AndroidCaldavSyncAdapater#131]
Following NullPointerExceptions leads to an "Caldav sync error (general)" error message. Can't sync since 2 days...

10-30 15:57:48.445: E/SyncAdapter(28858): Updating calendar exception java.lang.NullPointerException
10-30 15:57:48.445: E/SyncAdapter(28858): java.lang.NullPointerException
10-30 15:57:48.445: E/SyncAdapter(28858):   at org.gege.caldavsyncadapter.caldav.xml.MultiStatusHandler.endElement(MultiStatusHandler.java:56)
10-30 15:57:48.445: E/SyncAdapter(28858):   at org.apache.harmony.xml.ExpatParser.endElement(ExpatParser.java:156)
10-30 15:57:48.445: E/SyncAdapter(28858):   at org.apache.harmony.xml.ExpatParser.appendChars(Native Method)
10-30 15:57:48.445: E/SyncAdapter(28858):   at org.apache.harmony.xml.ExpatParser.parseFragment(ExpatParser.java:497)
10-30 15:57:48.445: E/SyncAdapter(28858):   at org.apache.harmony.xml.ExpatParser.parseDocument(ExpatParser.java:484)
10-30 15:57:48.445: E/SyncAdapter(28858):   at org.apache.harmony.xml.ExpatReader.parse(ExpatReader.java:309)
10-30 15:57:48.445: E/SyncAdapter(28858):   at org.apache.harmony.xml.ExpatReader.parse(ExpatReader.java:267)
10-30 15:57:48.445: E/SyncAdapter(28858):   at org.gege.caldavsyncadapter.caldav.entities.CalendarEvent.setICSasMultiStatus(CalendarEvent.java:153)
10-30 15:57:48.445: E/SyncAdapter(28858):   at org.gege.caldavsyncadapter.caldav.CaldavFacade.getEvent(CaldavFacade.java:718)
10-30 15:57:48.445: E/SyncAdapter(28858):   at org.gege.caldavsyncadapter.caldav.entities.CalendarEvent.fetchBody(CalendarEvent.java:262)
10-30 15:57:48.445: E/SyncAdapter(28858):   at org.gege.caldavsyncadapter.caldav.entities.CalendarEvent.updateAndroidEvent(CalendarEvent.java:959)
10-30 15:57:48.445: E/SyncAdapter(28858):   at org.gege.caldavsyncadapter.syncadapter.SyncAdapter.synchroniseEvents(SyncAdapter.java:345)
10-30 15:57:48.445: E/SyncAdapter(28858):   at org.gege.caldavsyncadapter.syncadapter.SyncAdapter.onPerformSync(SyncAdapter.java:170)
10-30 15:57:48.445: E/SyncAdapter(28858):   at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:254)

**Comment by timoberger** [comment]
this bug is already known #129 and will be fixed within the next release.
thanks for reporting.
feel free to reopen if needed
