### ISSUE TITLE
NullPointerException in MultiStatusHandler on 404 status

### ISSUE THREAD

**Issue by ndl** [gggard/AndroidCaldavSyncAdapater#132]
Synchronization fails for me for Apple CalendarServer installation with NullPointerException @ MultiStatusHandler (STATUS end tag handling).

It seems the reason is that on 404 status there's no PROPSTAT in the result, so mPropStat is never initialized. This patch https://gist.github.com/ndl/7293258 fixes it for me and allows to finish synchronization successfully.

**Comment by timoberger** [comment]
duplicate of #131 and #129
