### ISSUE TITLE
Unicode characters garbled

### ISSUE THREAD

**Issue by bytepossum** [gggard/AndroidCaldavSyncAdapater#135]
If I add or change event containing Cyrillic (Unicode) characters, they are converted to question marks after sync (both on Android and server). Latin characters are OK.

Событие ⟶ ???????

I use ownCloud 5.0.13 and CaldavSyncAdapter 1.8. Thunderbird Lightning sync works fine.

**Comment by timoberger** [comment]
can you send me this event as ics-file?

**Comment by bytepossum** [comment]
Here's the new event I exported from my phone right after creation: [event_before.vcs](http://glesik.ru/share/event_before.vcs). And this is the one exported from ownCloud web interface after sync: [event_after.ics](http://glesik.ru/share/event_after.ics).

**Comment by timoberger** [comment]
this is a bug within the sync adapter. i will fix this soon and provide a new beta-file.

**Comment by timoberger** [comment]
please test my latest release v1.8.1-beta.2
https://github.com/timoberger/AndroidCaldavSyncAdapater/releases/tag/v1.8.1-beta.2

**Comment by bytepossum** [comment]
Fixed for me with v1.8.1-beta.2. Thank you!

**Comment by timoberger** [comment]
thanks for the report.
