### ISSUE TITLE
Kitkat 4.4 can't open app

### ISSUE THREAD

**Issue by Wikunia** [gggard/AndroidCaldavSyncAdapater#138]
Unfortunately I have a problem with my Nexus 5 running Android 4.4 Kitkat. I can install CalDAV Sync Free Beta, but I can't open it! There is no icon and in Google Play there is only the button "uninstall" but no "open" :(
I hope you can fix it! ;)

Thanks!

**Comment by timoberger** [comment]
you can add new caldav accounts in
settings -> accounts -> new account -> caldav sync adapter
there you can enter your credentials.

**Comment by Wikunia** [comment]
Ah perfect I am New to Android so I didn't know this kind of application.
Thanks
