### ISSUE TITLE
Sync loop-events on the past dates

### ISSUE THREAD

**Issue by er4** [gggard/AndroidCaldavSyncAdapater#142]
I created my calendar a few years ago and over the years has established a lot of looping events like "every second saturday". When the event takes place, I always remove it from calendar.
But when I synchronize calendar, all the looped events on Android calendar creates not only in the future, but in the past too to date of this events creation.
If it not possible track correctly deleted events in events loop-line and the server passes only information about their creation, it would be useful option "synchronize events from the //random date//", cause manually delete all this years impossible.

**Comment by timoberger** [comment]
see issue #141

**Comment by er4** [comment]
oh lol, ok. didn't notice the obvious when post it.
