### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by jiremek** [gggard/AndroidCaldavSyncAdapater#15]
CalDav Sync plante lorsqu'on l'active en synchronisation ou que l'on décide d'activier ce calendrier (S agenda ou Google Agenda).
Version 1.4
Toujours en http

**Comment by gggard** [comment]
Merci de ce retour, est-ce que vous avez envoyé un rapport avec l'interface Android ? Si oui, est-ce que vous pouvez
me donner approximativement l'heure du rapport et si possible dans les details du rapport le nom de l'exception qui est renvoyée ?
Merci

**Comment by jiremek** [comment]
J'en fait un dès a présent.
Java.lang.NullPointerException
Methos: getCaledarEvents
Ligne: 289

**Comment by gggard** [comment]
OK, j'ai eut le rapport de test, j'ouvre un nouveau bug #22 avec la trace et je clos celui là, merci !
