### ISSUE TITLE
App installed but not showing on xperia mini pro (android 4.04)

### ISSUE THREAD

**Issue by carolntsi** [gggard/AndroidCaldavSyncAdapater#154]
Hi,
I've downloaded the app from Play Store. The download was allright, and I can see the app in the App list of the Settings menu of my phone, BUT no shortcut has been created so I can't launch it.
It seems no one had this issue before, so maybe it has something to do with my phone ?
(I've uninstalled and re-installed the app twice).
Thanks if you have a hint for this !

Carole

**Comment by Ruud68** [comment]
Hi, you can find the icon for this app in 'Settings' > 'Accounts' > '+ new account'. Here you can choose 'CalDav Sync Adapter'.

hope this helps.
regards, Ruud

**Comment by carolntsi** [comment]
Thanks a lot !
It was not easy to find for a newbie like me ;-)
