### ISSUE TITLE
Caldav sync error (general)

### ISSUE THREAD

**Issue by dajusc** [gggard/AndroidCaldavSyncAdapater#157]
I use the CalDAVSyncAdapter V1.8 to with ownCloud. After importing an iCal file (google calendar export) into ownCloud, the sync on my phone failed with the message "Caldav sync error (general)". Thunderbird calendar and ownCloud-GUI displayed all calendar entries as expected.

Figured out the problem was caused by the time-entries in the *.ics-file, which are full day events and had the same start and end date:
DTSTART;VALUE=DATE:20131206
DTEND;VALUE=DATE:20131206

After deleting the ownCloud calender, manually editing all entries in the *.ics file like:
DTSTART;VALUE=DATE:20131206
DTEND;VALUE=DATE:20131207
and importing it again into ownCloud, CalDAVSyncAdapter syced like a charm.

You could probably argue that it's rather a problem with ownCloud than with CalDAVSyncAdapter, as ownCloud does not seem to check the integrity of the calendar correctly. Anyway this issue report maybe helps someone with similar problems. But perhaps the CalDAVSyncAdapter could also be made more robust regarding inconsistent entries in future versions?

Cheers
David

**Comment by blausand** [comment]
Yes, at least an ID of the faulty entry would help.
I have "unknown events in ICS" error rather than the "general" Caldav sync Error

**Comment by Frodox** [comment]
I have same issue after importing a _.vcs_ file.
Server: ownCloud, trying to import over HTTP. Android 4.3

**Comment by derjohn** [comment]
+1 here. Owncloud 8.2.2
