### ISSUE TITLE
colors will not be imported

### ISSUE THREAD

**Issue by albialbi** [gggard/AndroidCaldavSyncAdapater#16]
Colors from calendar are not importet.
At least not from owncloud 4.56

**Comment by jiremek** [comment]
There is no color associated to an event in caldav, just a category of event.
Your calendar software associate a category to a color !
In android calendar software, each calendar have a color and that all.

**Comment by albialbi** [comment]
I have my own calendar and 4 shared. These have different colors in owncloud. After sync colors are wrong.

**Comment by jiremek** [comment]
Ok
So each calendar have one color ? exact ?
If I'm right, each color depends on the software used, color choice doesn't lie to the calendar, but only to the software (include website based calendar).

**Comment by albialbi** [comment]
yes correct. When I use Acal I get the colors from owncloud.

**Comment by jiremek** [comment]
With this apps, you could and should use a normal calendar apps like google agenda or "S Agenda" on Galaxy smartphone.
This apps permit to use like "natively" the caldav in any android calendar apps

**Comment by gggard** [comment]
I tag it as enhancement, it seams that it is a owncloud specific feature that has been integrated into acall...
The first enhancement is ... which manage the colors of the calendar
I will check if it is possible to get the information from the owncloud caldav interface...

**Comment by chspnk** [comment]
gggard: so your test account will stay up of course, if there's anything else i can do to help, just tell me!

**Comment by timoberger** [comment]
import of calendar colors will be implemented within the next release.
it is tested against SabreDAV (and so also owncloud) and i have seen someone reporting from sogo.
