### ISSUE TITLE
Manage calendar colors

### ISSUE THREAD

**Issue by gggard** [gggard/AndroidCaldavSyncAdapater#17]
For the moment the calendar colors are not set, provide a mean to have different colors for the calendars.

**Comment by woyczek** [comment]
Why not using an open source library, like http://code.google.com/p/caldav4j/ ?
It supports write access, and all colours.

But I dont know the work it would be to rewrite the connector using this lib.

**Comment by gggard** [comment]
We use indeed a library for parsing iCal files which  is iCal4J (http://ical4j.sourceforge.net/), I did fork it in the source code of the app to correct problems with android integration, at the time I do this choice (vs for example caldav4j) that's because I was not able to integrate cleanly with the ICS account & calendar framework others libs (incl. caldav4j).

Perhaps it was by not knowing how the caldav4j api is working, if it is the case, do not hesitate to contribute (I put in place a caldav facade just in case of this kind of decisions).

Thanks for the idea !

**Comment by woyczek** [comment]
"Gérald GARCIA" notifications@github.com a écrit :

> We use indeed a library for parsing iCal files which  is iCal4J
> (http://ical4j.sourceforge.net/), I did fork it in the source code of
> the app to correct problems with android integration, at the time I do
> this choice (vs for example caldav4j) that's because I was not able to
> integrate cleanly with the ICS account & calendar framework others libs
> (incl. caldav4j).
> 
> Perhaps it was by not knowing how the caldav4j api is working, if it is
> the case, do not hesitate to contribute (I put in place a caldav facade
> just in case of this kind of decisions).
> 
> Thanks for the idea !
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/gggard/AndroidCaldavSyncAdapater/issues/17#issuecomment-15394070

En fait, je ne sais pas non plus si c'est par méconnaissance, avais toutefois l' impression que les librairies utilisées étaient très différentes. 

## Quoi qu'il en soit, je vais tacher de creuser pour activer le read / write  et la gestion des couleurs... sans garantie.  

Gaétan RYCKEBOER,
© Air Android

**Comment by krzd** [comment]
Maybe choose random colours for the calendars or provide an option for the user to set a colour for the calendars, until they can be properly synced. It would be already a huge enhancement if you could distinguish the different calendars, most users probably don't care if the colours match.

**Comment by chspnk** [comment]
I also think random colors or a custom set colour is the way to do it. As far as i know, Lightning does it the same way.

**Comment by gggard** [comment]
OK, I will implement a random color into a predefined set (I wonder if purely random colors can give good results ;-) )

**Comment by woyczek** [comment]
"Gérald GARCIA" notifications@github.com a écrit :

> OK, I will implement a random color into a predefined set (I wonder if
> purely random colors can give good results ;-) )
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/gggard/AndroidCaldavSyncAdapater/issues/17#issuecomment-16077151

Perheaps, a value in a config xml file ?
1/ the color will always be the same. ;

## 2/ one would be able to force the colour. Its not unusual to have more than five cals, the color code is then important.

Gaétan RYCKEBOER

"Le problème des citations sur internet, c'est qu'on ne peut jamais être sûr de leur véracité." 
-- Abraham LINCOLN
