### ISSUE TITLE
Accept directly calendar uri in stead of principal uri

### ISSUE THREAD

**Issue by gggard** [gggard/AndroidCaldavSyncAdapater#18]
Make the apps understand that the given URL is not pointing to principals but directly to a particular calendar

**Comment by roidelapluie** [comment]
without this it won't work for Zimbra..

**Comment by gggard** [comment]
Agreed, will implements this

**Comment by spineaker** [comment]
Still not working with owncloud on v1.5.

**Comment by Arooo** [comment]
Hi gggard,

1.5, Still no chance either with Communigate pro, got "Unknown error" :/

Is there a way for us to give you back some more explicit feedback ? The only entry I can find in catlog is "TestConnection".

**Comment by chspnk** [comment]
I have to add that on my android the CalDAV Sync Adapter crashes when syncing with my owncloud (calendar URL). Don't know why..
[edit] I guess I have to lern reading one more time ;) It's just like spineaker said...

**Comment by timoberger** [comment]
this is already done. -> closing
