### ISSUE TITLE
Caldav sync error (IO): The target server failed to respond

### ISSUE THREAD

**Issue by Griffon26** [gggard/AndroidCaldavSyncAdapater#189]
I've been debugging a problem that I'm having when syncing my phone with the egroupware calendar on my home server.

My phone syncs correctly when it's on my own wifi network, but when I sync it from over the internet it reports "Caldav sync error (IO): The target server failed to respond"

I've captured on both my phone and on my router and it looks like PROPFIND requests are coming through fine, but the REPORT request that follows is lost before it reaches my router. As a result, 15 seconds after the server sent its last reply (KeepAliveTimeout), it terminates the connection and the sync adapter reports the sync error.

Is there anything special about REPORT requests? Could it be that there's an http proxy in between that drops those messages? Do you have any idea what else I can do to debug this?

**Comment by Griffon26** [comment]
I contacted vodafone support and it turns out their AP does some filtering, apparently for security. When I switched to their "unsecure" AP the problem disappeared. I haven't figured out why the problem was specific to REPORT requests, but for the time being I'll consider it a bug in their configuration. If anyone encounters this problem again let me know.

**Comment by jkufner** [comment]
If PROPFIND is handled differently than REPORT requests by provider's infrastructure, it means that your communication is not encrypted or your provider succesfully performed MITM attack on you. If it is the first case, AndroidCaldavSyncAdapater must be fixed (encryption must be mandatory). If it is the second case, you are in trouble.
