### ISSUE TITLE
"Invalid server answer, check URL"

### ISSUE THREAD

**Issue by paulrrogers** [gggard/AndroidCaldavSyncAdapater#199]
Used to work with my Owncloud server. After moving from a subdomain on DynDNS.org to a subdomain on NoIP.me it now produces this error.

Running Caldav Sync Beta on Andriod 4.3.

**Comment by paulrrogers** [comment]
Turns out I forgot to append the correct path as I had in the past:
http(s)://server/owncloud base/remote.php/caldav/principals/user_name
From:
https://github.com/gggard/AndroidCaldavSyncAdapater/wiki/Server-Compatibility-List

**Comment by gluhovsky** [comment]
Same problem with server: http://calendar.male.ru
