### ISSUE TITLE
Updated Events not synchronized

### ISSUE THREAD

**Issue by kedarbhise** [gggard/AndroidCaldavSyncAdapater#213]
New event is added correctly on my Android.
If the original author sends out an update, the event is updated correctly on my original calendar on the server. However, the event on Android is never updated, even after choosing "Refresh" from the Calendar menu.

Environment:
- Android 4.2.1
- Zimbra Server 8.0.7
- Caldav Sync Free Beta 1.8.1

**Comment by matejsvajger** [comment]
I'd like to confirm the same problem. I can create events, with the adapter, but any further updates in both directions are impossible. Either I update it on the server, or on Android, the changes never go through.

Tested Caldav SyncAdapter 1.8.1 on Android 4.4.3, with server running on SabreDAV 2.0.4

**Comment by kedarbhise** [comment]
No longer using Caldav SyncAdapter for Synchronizing Calendars.
Gmail app is able to handle the synchronization correctly.
Also, Outlook on Android is quite capable on its own to support any Microsoft mail servers such as Exchange and Office 365.
