### ISSUE TITLE
Repository typo "Adapater" rather than "Adapter"?

### ISSUE THREAD

**Issue by hartwork** [gggard/AndroidCaldavSyncAdapater#237]
Am I the first to notice the typo? Is it purpose? Did you decide against a rename?
Best, Sebastian

**Comment by arregit** [comment]
I have to confess I didn't noticed, and it's been a whole year. Shame on
me!! XD

**Comment by gggard** [comment]
Typical mix of french "adaptateur" and English counterpart... ;-)
I believe we will have to live with it ;-)
Gérald

Le 20 avril 2015 18:05:51 GMT+02:00, Arregi notifications@github.com a écrit :

> I have to confess I didn't noticed, and it's been a whole year. Shame
> on
> me!! XD
> On Apr 20, 2015 5:29 PM, "Sebastian Pipping" notifications@github.com
> wrote:
> 
> > Am I the first to notice the typo? Is it purpose? Did you decide
> > against a
> > rename?
> > Best, Sebastian
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/gggard/AndroidCaldavSyncAdapater/issues/237.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/gggard/AndroidCaldavSyncAdapater/issues/237#issuecomment-94494565

## 

Envoyé de mon téléphone. Excusez la brièveté.

**Comment by hartwork** [comment]
Closing to keep https://github.com/issues clean for myself…
