### ISSUE TITLE
Does not work with Communigate pro server

### ISSUE THREAD

**Issue by Arooo** [gggard/AndroidCaldavSyncAdapater#24]
Hi gggard,

   Tried a few CalDAV providers, but the one I actualy need is Communigate Pro server. The URL provided by this server is formed as :
https://server_addres/CalDAV/~username/name_of_the_calendar
This URL works perfectly with thunderbird/lightning, butAndroidCaldavSyncAdapter returns :
"Invalid server answer, check URL"

Sure you will get it. Keep the good work :)

Arooo

**Comment by gggard** [comment]
Are you sure that https://server_addres/CalDAV/~username/ does not work ?
If not, please wait for #18, which should solve your problem.

**Comment by Arooo** [comment]
Yes, I tried both https://....../~username and https://....../~username/calendarName, neither of those will work :/ , anyway, you're right, I first didn't pay too much attention to #18, which when it is solved, will probably fix the issue for most of DAVs servers. This issue and some others could probably be tagged duplicate to this one.

Thx a lot.

**Comment by gggard** [comment]
Put it as duplicate from #18, if needed after new release reopen it !
