### ISSUE TITLE
Doesn't work with iCloud

### ISSUE THREAD

**Issue by modelno1** [gggard/AndroidCaldavSyncAdapater#25]
Gives me "Invalid server answer, check URL". Running adapter 1.4 on ICS 4.0.3.

**Comment by gggard** [comment]
Perhaps it is linked to #18, let wait for the new version and see if it fixes you problem

**Comment by gggard** [comment]
Mark it as duplicate of #18, if needed reopen it !

**Comment by modelno1** [comment]
After updating iCloud still gives me "Invalid server answer, check URL".

**Comment by krzd** [comment]
Works fine for me. I had the same message first when I entered the full address without trailing slash. I used the full server address in the form https://pXX-caldav.icloud.com:443/YY/principal/, replace XX and YY with appropriate details which I obtained on my mac in ~/Library/Calendars/...

**Comment by gggard** [comment]
Thanks krzd for the report, I close
