### ISSUE TITLE
No calendars show up with a https self-signed certificat

### ISSUE THREAD

**Issue by GuilloOme** [gggard/AndroidCaldavSyncAdapater#26]
Hi,
I recently setup a https interface on my owncloud server based on a self-signed certificate.

For testing purpose, I set 2 accounts on my android device. Both with the same username/password but one through http and the other one through https (with a self-signed certificate). The one on http work well (sign-in, show my calendars and sync) but the one on https sign-in but never show me my calendars (and never sync).

I can provide a test account if needed…

Thanks,

**Comment by gggard** [comment]
Do you mean that you have on the same android two accounts ?
If yes, I think there is a bug in the account management (the account name is the user name), please confirm, I will then open another bug...

**Comment by GuilloOme** [comment]
After reading you, I try on 2 different android device (one on http and the other on https). It's work well on the two devices.
So I tried to reproduce the first bug… unsuccessfully…

At least, I can confirm that the https self-signed is NOT a issue. 
But, I CAN'T confirm there is a bug with the account management…
