### ISSUE TITLE
Events in Android are not deleted when deleted on server

### ISSUE THREAD

**Issue by marco2bb2** [gggard/AndroidCaldavSyncAdapater#27]
Syncing with sogo is ok adding events (they appears in Android Calendar after sync), but events deleted in sogo are not removed from Android Cal after synv

**Comment by gggard** [comment]
Will be corrected soon

**Comment by timoberger** [comment]
i have set up a test version. please see #86 
i will close this one to get an overview of all unhandled issues.
feel free to reopen when needed.
