### ISSUE TITLE
Support Recurring events

### ISSUE THREAD

**Issue by laoneo** [gggard/AndroidCaldavSyncAdapater#30]
With a sabredav installation as server your app shows recurring event as single event.

**Comment by gggard** [comment]
Agreed to be corrected

**Comment by laoneo** [comment]
Do you have a timefrime when it will be corrected. Perhaps I can give you a hand as I have played around quite a little bit with rrules and this ical stuff....

**Comment by gggard** [comment]
Of course it will be very nice that you make me a patch to implements this if you have already played with it !
Thanks in advance !

**Comment by laoneo** [comment]
I wanted to say if you need some help working with rrules. I've never done some android app programming (but I know java very well). When you can give me a short introduction how to setup the dev environment I will see if I can start implementing this missing feature...

**Comment by gggard** [comment]
Should be ok in the last release, reopen if needed

**Comment by laoneo** [comment]
thanks
