### ISSUE TITLE
FATAL EXCEPTION: SyncAdapterThread-1

### ISSUE THREAD

**Issue by switchgott** [gggard/AndroidCaldavSyncAdapater#31]
Hi,
first to say, big thanks for your work, to create a caldav sync adapter :-)
I have a small problem to sync with owncloud.
I could reach the server, but sync nothing from and to it.

Get a Java exception error.
Use galaxy s2 with android 4.1.2.

Big thanks for help
Bye

dmesg error:

D/CaldavFacade(22067): HttpResponse status=HTTP/1.1 207 Multi-status body= <?xml version="1.0" encoding="utf-8"?><d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:cal="urn:ietf:params:xml:ns:caldav" xmlns:cs="http://calendarserver.org/ns/"><d:response><d:href>/owncloud/remote.php/caldav/calendars/XXX/defaultcalendar//d:href<d:propstat><d:prop><d:resourcetype><d:collection/>cal:calendar//d:resourcetype/d:prop<d:status>HTTP/1.1 200 OK/d:status/d:propstat/d:response/d:multistatus
D/STATUSBAR-NetworkController( 2288): onDataActivity: direction=3
D/STATUSBAR-NetworkController( 2288): refreshSignalCluster: data=2 bt=false
D/CaldavFacade(22067): HttpResponse status=HTTP/1.1 207 Multi-status body= <?xml version="1.0" encoding="utf-8"?><d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:cal="urn:ietf:params:xml:ns:caldav" xmlns:cs="http://calendarserver.org/ns/"><d:response><d:href>/owncloud/remote.php/caldav/calendars/XXX/defaultcalendar//d:href<d:propstat><d:prop><d:resourcetype><d:collection/>cal:calendar//d:resourcetype/d:prop<d:status>HTTP/1.1 200 OK/d:status/d:propstat/d:response<d:response><d:href>/owncloud/remote.php/caldav/calendars/XXX/defaultcalendar/afae38cc-ffa8-492b-a6f7-47a45258b2c5.ics/d:href<d:propstat><d:prop><d:resourcetype/>/d:prop<d:status>HTTP/1.1 200 OK/d:status/d:propstat/d:response<d:response><d:href>/owncloud/remote.php/caldav/calendars/XXX/defaultcalendar/22bf7fd8-8c9a-439f-b799-bf27dcfa6efa.ics/d:href<d:propstat><d:prop><d:resourcetype/>/d:prop<d:status>HTTP/1.1 200 OK/d:status/d:propstat/d:response<d:response><d:href>/owncloud/remote.php/caldav/calendars/XXX/defaultcalendar/4b62a552-88e1-422a-bf2d-adbe4b2b45bc.ics/d:href<d:propstat><d:prop><d:resourcetype/>/d:prop<d:status>HTTP/1.1 200 OK/d:status/d:propstat/d:response/d:multistatus
E/SyncAdapter(22067): Updating calendar exception java.lang.NullPointerException
E/SyncAdapter(22067): java.lang.NullPointerException
E/SyncAdapter(22067):   at org.apache.http.impl.client.DefaultRequestDirector.rewriteRequestURI(DefaultRequestDirector.java:272)
E/SyncAdapter(22067):   at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:383)
E/SyncAdapter(22067):   at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:670)
E/SyncAdapter(22067):   at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:531)
E/SyncAdapter(22067):   at org.gege.caldavsyncadapter.caldav.CaldavFacade.updateCalendarInfos(CaldavFacade.java:605)
E/SyncAdapter(22067):   at org.gege.caldavsyncadapter.caldav.CaldavFacade.getCalendarList_method1(CaldavFacade.java:581)
E/SyncAdapter(22067):   at org.gege.caldavsyncadapter.caldav.CaldavFacade.getCalendarList(CaldavFacade.java:320)
E/SyncAdapter(22067):   at org.gege.caldavsyncadapter.syncadapter.SyncAdapter.onPerformSync(SyncAdapter.java:101)
E/SyncAdapter(22067):   at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:254)
W/dalvikvm(22067): threadid=11: thread exiting with uncaught exception (group=0x41a6e2a0)
E/AndroidRuntime(22067): FATAL EXCEPTION: SyncAdapterThread-1
E/AndroidRuntime(22067): java.lang.RuntimeException: java.lang.NullPointerException
E/AndroidRuntime(22067):        at org.gege.caldavsyncadapter.syncadapter.SyncAdapter.onPerformSync(SyncAdapter.java:126)
E/AndroidRuntime(22067):        at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:254)
E/AndroidRuntime(22067): Caused by: java.lang.NullPointerException
E/AndroidRuntime(22067):        at org.apache.http.impl.client.DefaultRequestDirector.rewriteRequestURI(DefaultRequestDirector.java:272)
E/AndroidRuntime(22067):        at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:383)
E/AndroidRuntime(22067):        at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:670)
E/AndroidRuntime(22067):        at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:531)
E/AndroidRuntime(22067):        at org.gege.caldavsyncadapter.caldav.CaldavFacade.updateCalendarInfos(CaldavFacade.java:605)
E/AndroidRuntime(22067):        at org.gege.caldavsyncadapter.caldav.CaldavFacade.getCalendarList_method1(CaldavFacade.java:581)
E/AndroidRuntime(22067):        at org.gege.caldavsyncadapter.caldav.CaldavFacade.getCalendarList(CaldavFacade.java:320)
E/AndroidRuntime(22067):        at org.gege.caldavsyncadapter.syncadapter.SyncAdapter.onPerformSync(SyncAdapter.java:101)
E/AndroidRuntime(22067):        ... 1 more
E/android.os.Debug( 2163): !@Dumpstate > dumpstate -k -t -z -d -o /data/log/dumpstate_app_error

**Comment by dlech** [comment]
Hi. I just stated using owncloud and would like to get this to work too. I have a patch that should fix this crash. See issue #38.

**Comment by timoberger** [comment]
this looks pretty old.
feel free to reopen when needed.

**Comment by Ramkumarcs31** [comment]
Hi , It was so good and its really interesting. may i know the reason for this exception and how you fixed it ?
