### ISSUE TITLE
SOGo connection

### ISSUE THREAD

**Issue by GortiZ6** [gggard/AndroidCaldavSyncAdapater#32]
Trying to connect to a SOGo calendar i can add the account correctly, but when I click on "Sync" after few seconds I get a FC

**Comment by nodiscc** [comment]
What's an FC? Do you still have this problem?

**Comment by GortiZ6** [comment]
FC stands for Force Close. Anyway, I've re-installed version 1.7 and now it seems to work fine, thank you!! :)

**Comment by nodiscc** [comment]
@GortiZ6 glad it works, can you close this issue?

**Comment by GortiZ6** [comment]
After the first sync (on install) I still have the application not working. When it closes it asks me if I want a Report, but when I click on the button it just says that the google play store have been closed (but this one I think is an error due to my version of android which probably doesn't support the android logger)
I'm using the last version on the play store (1.7) with SOGo version 2.0.5a (latest from their repository for Ubuntu 12.04)
Let me know if i can help some how

**Comment by wilbertvolkers** [comment]
Could it be related to my problem: https://github.com/gggard/AndroidCaldavSyncAdapater/issues/89 ?
Both the Calendar and CalDavSync stop working due to the Calendar color that is returned by SOGo.

**Comment by timoberger** [comment]
the sync adapter did not read the calendar color in V1.7

**Comment by GortiZ6** [comment]
Yes, it can be. Are you going to upload a new version to the play store? How can I test if this fix my issue?

**Comment by timoberger** [comment]
i just release the unofficial version V1.8-alpha-2
Please keep in mind that i am NOT the official maintainer for this project.
I do not guarantee that my version of "caldav sync adapter" works. Nor do i guarantee that this software won't destroy your data.
https://github.com/timoberger/AndroidCaldavSyncAdapater/releases/tag/V1.8-alpha-2

**Comment by timoberger** [comment]
not needed anymore?

**Comment by GortiZ6** [comment]
I couldn't test your alpha version, but I trust you and I'll wait for the 1.8 version (I've seen that even if it force close, starting it a couple of times downloads the calendars in any case [at least the one that I need]) 
If in 1.8 it wont work I'll re-open this bug ;)
