### ISSUE TITLE
DAVICAL

### ISSUE THREAD

**Issue by AdamN1** [gggard/AndroidCaldavSyncAdapater#34]
When you add a new account synchronization is working correctly. unfortunately, with the addition of a new record from the adnroid there is no synchronization.
Sync does not work also with the new data on CalDAV Server

**Comment by gggard** [comment]
For the sync from android to server, it is normal, for the moment I prefer to be sure that the app is sufficiently stable before introiducing the sync (there is a risk of dropping all the events on the server if something goes very wrong...)

For "Sync does not work also with the new data on CalDAV Server", could you give me more information (server, error message if any,...)

**Comment by blausand** [comment]
**Thanks a million for a native FOSS CalDAV connector!**
- I accidentally added some events on android, which don't sync with DAViCal now.
  <br>Is there a way to export/transport calendar data?
- Can we expect the two way sync to start in may or so?

**Comment by AdamN1** [comment]
unfortunately at the moment sync from the server and to server is not working
If you try to sync davical returns error logs
"davical: LOG: request:Request is "PROPFIND" but client set content-type to "text/plain". Assuming they meant XML!"

**Comment by timoberger** [comment]
2way sync is on the way and content-type has been changed.
feel free to reopen when needed.
