### ISSUE TITLE
"This password is incorrect" - Nexus 7 - SabreDAV

### ISSUE THREAD

**Issue by damienaguerre** [gggard/AndroidCaldavSyncAdapater#35]
Je n'arrive pas à me connecter à mon compte caldav sur mon serveur sabredav avec ma nexus 7. Pourtant, cela fonctionne sur iPhone et même sur Android avec l'application payante caldav sync.

Merci et bravo pour le travail que tu réalise

**Comment by gggard** [comment]
Bonsoir et merci

Est-ce que la nouvelle version résout le problème ?

**Comment by damienaguerre** [comment]
J'arrive maintenant à me connecter, mais je suis obligé d'entrer l'url complète, je m'explique :

Avec iOS ou l'autre appli Android, je dois seulement entrer l'url : monserveur.com.

Pour que ça fonctionne, j'ai ajouté ce .htaccess à la racine de mon serveur web :

#Utilisé pour l'url d'ajout de compte caldav sur les périphériques

#-- Android --#
RedirectPermanent /dav https://www.monserveur.com/lib/sabreDav/server.php

#-- iOS --#
RedirectPermanent /.well-known/caldav https://www.monserveur.com/lib/sabreDav/server.php

Mais avec votre appli, je pense que ce n'est pas (encore) pris en compte, et du coup je suis obligé d'entrer à la main : https://monserveur.com/lib/sabreDav/server.php/principals/username au lieu de : https://monserveur.com

Etant donné que je suis destiné à ajouter fréquemment des comptes, c'est assez contraignant..

Je crois que ce processus est expliqué ici : https://code.google.com/p/sabredav/wiki/ServiceDiscovery

Merci de votre réactivité

**Comment by timoberger** [comment]
well, hmm. i do not understand french.
hope this is ok, i will close this issue. feel free to reopen when needed.
