### ISSUE TITLE
Phone-requirements?

### ISSUE THREAD

**Issue by felixwb** [gggard/AndroidCaldavSyncAdapater#36]
Google tells me, this app is not compatible with my  Samsung GT-I5800-Device (Android 2.2, ARM11 667 MHz) ... so my question is: what are the exact requirements for this app to run on a phone?

**Comment by DavidWiesner** [comment]
Hy Felix,
Google published their Calendar-API in Android Ice Cream Sandwich so this App requires at least Android 4.0
regards,
David

**Comment by gggard** [comment]
I close this issue and mark it as duplicate of #13, Dominik publish a compatbility API for android <4.0, that can make the trick but we have to test it... stay tuned !
