### ISSUE TITLE
Two way sync radicale

### ISSUE THREAD

**Issue by switchgott** [gggard/AndroidCaldavSyncAdapater#39]
Hi,

i use radicale server git with 1.6 sync adapter and have the problem, 
that appointments are sync only from radicale but now back!
I meen tow way sync.
Does it not implemented yet?

Big thanks.

**Comment by HLFH** [comment]
@gggard I think it's almost stable. Please enable two way sync :)

**Comment by switchgott** [comment]
So , please, do it!
It would realy nice for all.

**Comment by varac** [comment]
two-way sync would be awesome ! any plans to include it ?

**Comment by nodiscc** [comment]
@gggard Is there a branch with two-way sync available?
Thanks

**Comment by ulrichard** [comment]
What is the timeframe for enabling two way sync.
I'd like to know it it's worth waiting a bit, or if I should look for something else.
I'm happy to beta test the feature, as I'm only slowly moving away from the google services.

**Comment by raoulbhatia** [comment]
any update on the two way sync?

**Comment by timoberger** [comment]
i have set up a test version.
please see #86 
i will close this issue to get an overview of all unhandled issues.
feel free to reopen when needed.
