### ISSUE TITLE
Duration in ical not supported

### ISSUE THREAD

**Issue by jspricke** [gggard/AndroidCaldavSyncAdapater#40]
Hi,

seems like the duration tag in ical is not supported in 1.7. Replacing it with a corresponding dtend works for a minimal example. Thanks for the great software!

**Comment by timoberger** [comment]
The "DURATION" is set, if "RRULE" or "RDATE" are set. DURATION and DTEND are not compatible.
This complies with the rules: For non-recurring events, you must include DTEND. For recurring events, you must include a DURATION in addition to RRULE or RDATE.
(see http://developer.android.com/guide/topics/providers/calendar-provider.html section "Adding Events")
If this doesn't work for you, please post an example of what you think is not working.

**Comment by timoberger** [comment]
note: "DURATION" is not being read from VEVENT at this time. For the time, it is being calculated from DTSTART and DTEND. Also the DTEND is not being calculated when only DTSTART and DURATION is set. (I didn't see this point within the rfc)

**Comment by jspricke** [comment]
As far as I read RFC5545 it's ok to use DURATION instead of DTEND. The ical export I use (rem2ics) does this and other software (like acal) works with it as well. But I guess I can hack around it, thanks :).

**Comment by gggard** [comment]
@jspricke I merged the timoberger pull request, should be implemented in the next release.

**Comment by jspricke** [comment]
Awesome, thanks a lot!

**Comment by timoberger** [comment]
looks pretty old.
feel free to reopen when needed.
