### ISSUE TITLE
VALARM tag sync

### ISSUE THREAD

**Issue by burnout75** [gggard/AndroidCaldavSyncAdapater#45]
BEGIN:VALARM
ACTION:DISPLAY
TRIGGER;VALUE=DURATION:-PT30M
DESCRIPTION:Descrizione personalizzata Mozilla
END:VALARM

This is the tag insert from Thunderbird by SOGo connector to ownCloud MySql db on creation/updating of VEVENT.

Events sync work as well but reminders are missing on all android devices.

**Comment by gggard** [comment]
Should work with recent merge, the next release will implement this (thanks David ;-) )

**Comment by timoberger** [comment]
pretty old.
feel free to reopen when needed.
