### ISSUE TITLE
Can't connect to google CalDav servers

### ISSUE THREAD

**Issue by KaitoKito** [gggard/AndroidCaldavSyncAdapater#50]
Hi,

Thanks for this very useful app. Unfortunately I can't connect to my google calendar.
When I'm typing my url ( which is like "https://www.google.com/calendar/dav/my.email.address@google.com/events" ) it keep saying "Wrong URL" with a white "!" on a red circle.

I know the url and my user/password are correct because on aCal (a very ugly calendar app) it work perfectly. If you can fix it that would be great.

Have a nice day.

KaitoKito.

P.S. I don't want google apps on my phone but at work we use google calendars...

**Comment by DavidWiesner** [comment]
Hy,
can you try to replace the "@"-sign with "%40" so like:
https://www.google.com/calendar/dav/my.email.address%40google.com/events

and try it again?
@gggard May the problem is related to this question http://stackoverflow.com/questions/14321873/java-url-encoding-urlencoder-vs-uri

**Comment by KaitoKito** [comment]
Hi,

I've tried it but nothing change...

**Comment by nodiscc** [comment]
For your information, Google has shut down public CalDAV access (http://googleblog.blogspot.de/2013/03/a-second-spring-of-cleaning.html). Maybe that explains your problem?

**Comment by KaitoKito** [comment]
I don't think so because it "will be shut down for other developers on September 16, 2013." according to your url. I'm pretty sure it's davey69's idea who is correct.

**Comment by timoberger** [comment]
google calendars are syncable with the next release.

feel free to reopen if needed.
