### ISSUE TITLE
Some Events not Synced

### ISSUE THREAD

**Issue by krzd** [gggard/AndroidCaldavSyncAdapater#55]
I have three events on next Monday which do not get synced to my phone, although a similar event I created simultaneously for Wednesday is displayed. I created those events some weeks ago, but did not notice that they are missing until now.
What can be the cause for this? Deactivating a calendar and re-activating it did not help.

//edit: Those events are in the same calendar.

**Comment by gggard** [comment]
Is it possible to send us the ics files corresponding to those events ?
Check first if there is no personnal data in it ;-)

**Comment by krzd** [comment]
Github does only allow images here, is there maybe any email address I can send it to? I would prefer not having it too public, anyway.

**Comment by krzd** [comment]
After adding a new event, the three missing events appeared on my phone.
The new event is synced properly, but the three formerly missing items appear as all day events, although they are only 1 hour events.

**Comment by timoberger** [comment]
the version 1.7 did have some bugs.
if you are interested you could try my current developer version https://github.com/timoberger/AndroidCaldavSyncAdapater/releases/tag/V1.8-alpha-2
i will close this issue to get an overview of all issues.
feel free to reopen when needed
