### ISSUE TITLE
CaldavProtocolException: At line 2, column 0: junk after document element

### ISSUE THREAD

**Issue by stepankonrad** [gggard/AndroidCaldavSyncAdapater#58]
I get the following error in logcat, if I want to connect to a caldav server via https. The server certificate is btw. self-signed.

D/CaldavFacade(21073): start testConnection 
E/CaldavFacade(21073): Force get calendars from 'https://<SERVER>/caldav.php/<CALENDAR>/home' failed org.gege.caldavsyncadapter.caldav.CaldavProtocolException: At line 2, column 0: junk after document element
I/SyncAdapter(21073): testConnection status=WRONG_ANSWER

**Comment by gggard** [comment]
What is the server ?
The URL : https:///caldav.php//home has been modified for the bug report ?

**Comment by stepankonrad** [comment]
Yes, I removed the URL, but it was correct. It is a private calendar, so I don't want to post it here, but I can send you an e-mail.
The format was something like https://DOMAIN/caldav.php/CALENDAR/home

**Comment by timoberger** [comment]
i hope this is fixed.
feel free to reopen when needed.
