### ISSUE TITLE
Connexion réussie mais pas d'agenda

### ISSUE THREAD

**Issue by minami-o** [gggard/AndroidCaldavSyncAdapater#6]
Bonjour,
Je parviens à connecter le compte et à activer la synchro, en revanche une fois dans Google Agenda, je vois bien mon compte, mais il n'y a aucun agenda associé.
Mon serveur caldav est baikal, un serveur (français!) simple mais efficace.
Je suis sous CyanogenMod10.1 sur mon Kindle Fire 2 et mon ZTE blade.
A noter qu'avec la version demo de AnDal, je parviens à me connecter, à synchroniser, à gérer mes agendas.
Je n'y connais pas grand-chose en dev sous android, mais je vais essayer de voir si je peux tirer quelque-chose de plus précis, ne serait-ce que pour voir si le problème vient de l'appli ou de ma config.

**Comment by gggard** [comment]
Merci de ce retour, est-ce que vous avez bien la version 1.2 ?
Si oui, pour davical il faut mettre une url du style : http(s)://serveur/caldav.php/utilisateur/
Pouvez-vous vérifier ? Merci d'avance

**Comment by minami-o** [comment]
Oui j'ai bien la version 1.2, que j'essaie de faire communiquer avec Google Agenda 4.2.1.
Les recommandations d'url pour baikal sont les suivantes : http(s)://serveur/cal.php/principals/utilisateur
C'est ce que j'ai utilisé avec succès pour AnDal, toute autre configuration échoue.
Pour CalSync Adapter, cela fonctionne aussi - la connexion est effective, c'est plus le dialogue avec l'application qui me semble problématique : le compte apparaît bien, mais le calendrier n'est pas reconnu, il ne s'affiche pas.
Impossible cependant d'obtenir un log quel qu'il soit, que ce soit pour la création du compte, pour la synchro, pour la consultation du compte dans Google Agenda...
L'application a-t-elle été testée avec GA 4.2.1 auparavant ?

**Comment by gggard** [comment]
C'est visiblement un problème avec baikal, je vais essayer de l'installer chez moi pour vérifier quel type de réponse il renvoie quand on demande la liste des calendars d'un agenda. Par contre je tombe sur https://github.com/jeromeschneider/Baikal/issues/12 sur ma machine, il faut que je trouve une autre solution...

**Comment by minami-o** [comment]
Je peux sans problème vous donner accès à un compte de test sur mon baikal perso dans la soirée, si ça suffit pour les tests...

**Comment by gggard** [comment]
Avec plaisir, ça m'évitera d'installer un LAMP pour ça ;-)
Me contacter directement par mail pour me donner les identifiants ;-)
Merci !

**Comment by gggard** [comment]
Thanks for the acccount minami-o, it is easy now ;-)

The problem is visibly that we can not rely on calendar-home-set property of davical to find calendars (currently we use a propfind on the principal with a depth parameter to 1 as work-arround), see CaldavFacade.java:297

On the other hand, the davical trick does not work on baikal... we will have to implement both solutions to get the calendards (if the davical solution does not get any result, let use the calendar-home-set).

I reaaly have doubt on the davical anwer to the query or I missed something

**Comment by minami-o** [comment]
Many thanks for your quick feedback!
Not sure to follow you on the details, but I think I get the logic.
Is there a chance that you implement this alternate calendar recovery solution?
I'd  gladly give a hand, but a look at the code made me realize I'm far too ignorant in java to provide any real help :/
I can at least stay available to test and/or provide test account(s) on my server...
Thanks anyway for your help and availability so far ;)

**Comment by gggard** [comment]
The implementation is foreseen for next release 1.4, hopefully somewhere at the end of this week, depend on the weather ;-)

**Comment by minami-o** [comment]
Wow excellent! I'll sure keep an eye on this and stay ready to test!

**Comment by gggard** [comment]
Should work with last fix

**Comment by minami-o** [comment]
As mentioned by mistake in issue 12, issue 6 is indeed fixed.
