### ISSUE TITLE
AndroidCaldavSyncAdapater crash

### ISSUE THREAD

**Issue by kmh42** [gggard/AndroidCaldavSyncAdapater#60]
I run my own ownCloud Server on a Raspberry Pi and tried to sync the Calendar with Android 4.1 on a Nexus S. The syncing went well, but after I reinstalled ownCloud on the server, the App now crashes every time when it tries to sync.

**Comment by axelsimon** [comment]
Could this have something to do with updating Owncloud to 5.0.6 ?
I updated recently and have started noticing this issue too.

Gard, would it be useful to share an Android Logcat taken during the crash?

**Comment by kmh42** [comment]
No. I still have 5.0.5. But I am now running Cyanogenmod 10.1 (Android 4.2) and I still have the same problem
Here is the crash report.
logcat:
D/dalvikvm(  798): GC_EXPLICIT freed 29K, 70% free 2380K/7692K, paused 2ms+2ms, total 23ms
D/dalvikvm(  767): GC_EXPLICIT freed 307K, 53% free 3645K/7692K, paused 14ms+6ms, total 103ms
I/ActivityManager(  355): Start proc org.gege.caldavsyncadapter for service org.gege.caldavsyncadapter/.syncadapter.SyncService: pid=16542 uid=10089 gids={50089, 3003, 1028}
V/SyncAdapter(16542): onPerformSync() on kmh42 with URL https://kmh42.no-ip.biz/remote.php/caldav/
W/Settings(  552): Setting auto_time_zone has moved from android.provider.Settings.System to android.provider.Settings.Global, returning read-only value.
D/AlarmManagerService(  355): Kernel timezone updated to -120 minutes west of GMT
W/SystemClock(  767): time going backwards: prev 68397018967868(ioctl) vs now 68397017800743(ioctl), tid=908
D/CaldavFacade(16542): 0 calendars found in set https://kmh42.no-ip.biz/remote.php/caldav/
D/CaldavFacade(16542): Found userPrincipal: https://kmh42.no-ip.biz/remote.php/caldav/principals/kmh42/
D/CaldavFacade(16542): 1 calendar-home-set found in https://kmh42.no-ip.biz/remote.php/caldav/principals/kmh42/
W/Settings(  552): Setting auto_time_zone has moved from android.provider.Settings.System to android.provider.Settings.Global, returning read-only value.
D/AlarmManagerService(  355): Kernel timezone updated to -120 minutes west of GMT
D/dalvikvm(13809): GC_EXPLICIT freed 90K, 70% free 2366K/7692K, paused 19ms+2ms, total 44ms
D/dalvikvm(14538): GC_EXPLICIT freed 795K, 65% free 2747K/7692K, paused 49ms+3ms, total 104ms
W/Settings(  552): Setting auto_time_zone has moved from android.provider.Settings.System to android.provider.Settings.Global, returning read-only value.
D/AlarmManagerService(  355): Kernel timezone updated to -120 minutes west of GMT
W/Settings(  552): Setting auto_time_zone has moved from android.provider.Settings.System to android.provider.Settings.Global, returning read-only value.
D/AlarmManagerService(  355): Kernel timezone updated to -120 minutes west of GMT
W/Settings(  552): Setting auto_time_zone has moved from android.provider.Settings.System to android.provider.Settings.Global, returning read-only value.
D/AlarmManagerService(  355): Kernel timezone updated to -120 minutes west of GMT
D/CaldavFacade(16542): 1 calendars found in set https://kmh42.no-ip.biz/remote.php/caldav/calendars/kmh42/
D/SyncAdapter(16542): Detected calendar name=ownCloud URI=https://kmh42.no-ip.biz/remote.php/caldav/calendars/kmh42/defaultcalendar/
D/SyncAdapter(16542): CTag has changed, something to synchronise
D/CaldavFacade(16542): Getting eTag by PROPFIND at https://kmh42.no-ip.biz/remote.php/caldav/calendars/kmh42/defaultcalendar/
D/CaldavFacade(16542): HttpResponse status=HTTP/1.1 207 Multi-status body= <?xml version="1.0" encoding="utf-8"?><d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:cal="urn:ietf:params:xml:ns:caldav" xmlns:cs="http://calendarserver.org/ns/"><d:response><d:href>/remote.php/caldav/calendars/kmh42/defaultcalendar//d:href<d:propstat><d:prop><d:getetag/>/d:prop<d:status>HTTP/1.1 404 Not Found/d:status/d:propstat/d:response<d:response><d:href>/remote.php/caldav/calendars/kmh42/defaultcalendar/owncloud-3ae77f282133810ea067fabebe416750.ics/d:href<d:propstat><d:prop><d:getetag>"3d0fd14f6915c74a3cbd501ccb0a693e"/d:getetag/d:prop<d:status>HTTP/1.1 200 OK/d:status/d:propstat/d:response<d:response><d:href>/remote.php/caldav/calendars/kmh42/defaultcalendar/owncloud-57c5bf42d8eef267cf88d6e09e905f01.ics/d:href<d:propstat><d:prop><d:getetag>"5511417db89152696a3623dd8e083c75"/d:getetag/d:prop<d:status>HTTP/1.1 200 OK/d:status/d:propstat/d:response<d:response><d:href>/remote.php/caldav/calendars/kmh42/defaultcalendar/owncloud-35b3a0a031c75a82e8c2b472f8d97e6e.ics/d:href<d:propstat><d:prop><d:getetag>"d343e06fe668c6d85800839513b6059e"/d:getetag/d:prop<d:status>HTTP/1.1 200 OK/d:status/d:propstat/d:response<d:response><d:href>/remote.php/caldav/calendars/kmh42/defaultcalendar/321d4299-5fcc-4ec9-a42d-4d096c03a554.ics/d:href<d:propstat><d:prop><d:getetag>"f8a6518e44f54f4b7c038c0a7c919a68"/d:getetag/d:prop<d:status>HTTP/1.1 200 OK/d:status/d:propstat/d:response<d:response><d:href>/remote.php/caldav/calendars/kmh42/defaultcalendar/85ec8a81-2f45-4d86-8881-0b4652874d58.ics/d:href<d:propstat><d:prop><d:getetag>"6529eb90c88fce520111eeae2badc2df"/d:getetag/d:prop<d:status>HTTP/1.1 200 OK/d:status/d:propstat/d:response<d:response><d:href>/remote.php/caldav/calendars/kmh42/defaultcalendar/27793704-849c-4c9c-849c-4dee98bec3cd.ics/d:href<d:propstat><d:prop><d:getetag>"2b45a3772c79ca574221d4089e2bf8e2"/d:getetag/d:prop<d:status>HTTP/1.1 200 OK/d:status/d:propstat/d:response/d:multistatus
D/SyncAdapter(16542): Event /remote.php/caldav/calendars/kmh42/defaultcalendar/owncloud-3ae77f282133810ea067fabebe416750.ics androidUri=null
D/CaldavFacade(16542): HttpResponse GET event status=HTTP/1.1 200 OK body= BEGIN:VCALENDAR
D/CaldavFacade(16542): VERSION:2.0
D/CaldavFacade(16542): PRODID:ownCloud Calendar
D/CaldavFacade(16542): BEGIN:VEVENT
D/CaldavFacade(16542): CREATED;VALUE=DATE-TIME:20130503T170520Z
D/CaldavFacade(16542): UID:ca72cb7d9e
D/CaldavFacade(16542): RRULE:FREQ=WEEKLY;INTERVAL=1;UNTIL=20130627
D/CaldavFacade(16542): LAST-MODIFIED;VALUE=DATE-TIME:20130503T170520Z
D/CaldavFacade(16542): DTSTAMP;VALUE=DATE-TIME:20130503T170520Z
D/CaldavFacade(16542): SUMMARY:Kontitionskurs
D/CaldavFacade(16542): DTSTART;VALUE=DATE-TIME:20130509T143000Z
D/CaldavFacade(16542): DTEND;VALUE=DATE-TIME:20130509T160000Z
D/CaldavFacade(16542): CLASS:PUBLIC
D/CaldavFacade(16542): LOCATION:USI SPitalgasse
D/CaldavFacade(16542): END:VEVENT
D/CaldavFacade(16542): END:VCALENDAR
I/Configurator(16542): ical4j.properties not found.
W/Sidekick_GmmLocationProviderImpl(16421): Unable to bind to GMM NLP
W/ActivityManager(  355): Unable to start service Intent { act=com.google.android.location.internal.GMM_NLP (has extras) } U=0: not found
E/JavaBinder(16380): **\* Uncaught remote exception!  (Exceptions are not yet supported across processes.)
E/JavaBinder(16380): java.lang.StringIndexOutOfBoundsException: length=1; index=1
E/JavaBinder(16380):    at com.android.calendarcommon2.Duration.parse(Duration.java:84)
E/JavaBinder(16380):    at com.android.providers.calendar.CalendarProvider2.calculateLastDate(CalendarProvider2.java:2862)
E/JavaBinder(16380):    at com.android.providers.calendar.CalendarProvider2.updateLastDate(CalendarProvider2.java:2917)
E/JavaBinder(16380):    at com.android.providers.calendar.CalendarProvider2.insertInTransaction(CalendarProvider2.java:2114)
E/JavaBinder(16380):    at com.android.providers.calendar.SQLiteContentProvider.insert(SQLiteContentProvider.java:96)
E/JavaBinder(16380):    at android.content.ContentProvider$Transport.insert(ContentProvider.java:201)
E/JavaBinder(16380):    at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:148)
E/JavaBinder(16380):    at android.os.Binder.execTransact(Binder.java:351)
E/JavaBinder(16380):    at dalvik.system.NativeStart.run(Native Method)
E/SyncAdapter(16542): Updating calendar exception java.lang.NullPointerException
E/SyncAdapter(16542): java.lang.NullPointerException
E/SyncAdapter(16542):   at org.gege.caldavsyncadapter.syncadapter.SyncAdapter.createAndroidEvent(SyncAdapter.java:312)
E/SyncAdapter(16542):   at org.gege.caldavsyncadapter.syncadapter.SyncAdapter.synchroniseEvents(SyncAdapter.java:173)
E/SyncAdapter(16542):   at org.gege.caldavsyncadapter.syncadapter.SyncAdapter.onPerformSync(SyncAdapter.java:136)
E/SyncAdapter(16542):   at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:254)
W/dalvikvm(16542): threadid=11: thread exiting with uncaught exception (group=0x418a9930)
E/AndroidRuntime(16542): FATAL EXCEPTION: SyncAdapterThread-1
E/AndroidRuntime(16542): java.lang.RuntimeException: java.lang.NullPointerException
E/AndroidRuntime(16542):    at org.gege.caldavsyncadapter.syncadapter.SyncAdapter.onPerformSync(SyncAdapter.java:149)
E/AndroidRuntime(16542):    at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:254)
E/AndroidRuntime(16542): Caused by: java.lang.NullPointerException
E/AndroidRuntime(16542):    at org.gege.caldavsyncadapter.syncadapter.SyncAdapter.createAndroidEvent(SyncAdapter.java:312)
E/AndroidRuntime(16542):    at org.gege.caldavsyncadapter.syncadapter.SyncAdapter.synchroniseEvents(SyncAdapter.java:173)
E/AndroidRuntime(16542):    at org.gege.caldavsyncadapter.syncadapter.SyncAdapter.onPerformSync(SyncAdapter.java:136)
E/AndroidRuntime(16542):    ... 1 more
W/Settings(  552): Setting auto_time_zone has moved from android.provider.Settings.System to android.provider.Settings.Global, returning read-only value.
D/AlarmManagerService(  355): Kernel timezone updated to -120 minutes west of GMT
W/Settings(  552): Setting auto_time_zone has moved from android.provider.Settings.System to android.provider.Settings.Global, returning read-only value.
D/AlarmManagerService(  355): Kernel timezone updated to -120 minutes west of GMT
W/Settings(  552): Setting auto_time_zone has moved from android.provider.Settings.System to android.provider.Settings.Global, returning read-only value.
D/AlarmManagerService(  355): Kernel timezone updated to -120 minutes west of GMT
I/Process (16542): Sending signal. PID: 16542 SIG: 9
W/InputMethodManagerService(  355): Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@41e3bae8 attribute=null, token = android.os.BinderProxy@4225deb0
I/ActivityManager(  355): Process org.gege.caldavsyncadapter (pid 16542) has died.

**Comment by kmh42** [comment]
Is there something new on this front?

**Comment by nodiscc** [comment]
@kmh42 do you happen to have reccuring events in your owncloud calendar?
Every time I set up reccuring events in Owncloud and sync it to my android device, crash ensues.
Can you retry syncing without these reccuring events?

**Comment by kmh42** [comment]
Thats true. When is delet all reccuring events it syncs. But i need reccuring events. Besides when I set a time for the event on owncloud, My android allway shows an full day event.

**Comment by nodiscc** [comment]
>  i need reccuring events

I need them too. I've reported this to https://github.com/gggard/AndroidCaldavSyncAdapater/issues/71

> when I set a time for the event on owncloud, My android allway shows an full day event.

Same for me, I guess you are using the build from https://f-droid.org/ ? This has been reported and fixed (see https://github.com/gggard/AndroidCaldavSyncAdapater/issues/53) but it's still not included in the APK builds. Someone on http://f-droid.org/forums/topic/caldav-sync-adapter/ suggested we ask the project developer to tag a new release here on github.

@gggard ping :)

**Comment by bor** [comment]
@gggard ping - please do it :)

**Comment by timoberger** [comment]
same as #53 
this should be fixed with the next release.
i will close this issue (to get an overview of all unhandled issues).
feel free to reopen when needed.

i have set up a test version in #86
