### ISSUE TITLE
Sync to Yandex

### ISSUE THREAD

**Issue by igkhv** [gggard/AndroidCaldavSyncAdapater#62]
Downloads only with server yandex. Boot from the device to Yandex no.
Settings:
User: login@yandex.ru
Password: password
URL: https://caldav.yandex.ru:443

**Comment by nodiscc** [comment]
This is a known problem (https://github.com/gggard/AndroidCaldavSyncAdapater/issues/39)
Pushing updates from android to the server is not available. You can only download changes from the server, not update it.

You should watch https://github.com/gggard/AndroidCaldavSyncAdapater/issues/39 and close this bug report (it's not specific to yandex).
