### ISSUE TITLE
"Unknown error"

### ISSUE THREAD

**Issue by ygoe** [gggard/AndroidCaldavSyncAdapater#63]
When I try to connect to my CalDAV server, it sits there testing the connection for 1 or 2 minutes and then just says "Unknown error".

My CalDAV server is the example server from SabreDAV which should also be used in numerous other products. But this is my very first effort in WebDAV and CalDAV. I can open up the URL in my desktop browser but don't know what the correct results would be.

This combination of SabreDAV (stable library but development example) and this Android connector (unstable?) is everything I have, no other clients to test. I don't know on which side the problem is, but "Unknown error" is definitely not helpful to find it out.

**Comment by pyus13** [comment]
Please let me know what exactly you are using in the url field during configuration.

**Comment by ygoe** [comment]
I've forgotten it meanwhile, sorry, that was too much time.

I've just retried it with the URL "http://unclassified.de/dav/calendarserver.php/principals/test/default" (user and pw are test) and got "Wrong URL". Also with numerous other variants and "admin" instead of "test" and leaving path segments out. It's set up according to this guide: http://code.google.com/p/sabredav/wiki/CalDAV So you could try it yourself as well.

**Comment by timoberger** [comment]
i am developing the CalDAV Sync Adapter with an older and the current version of SabreDAV.
the correct URL would be http://unclassified.de/dav/calendarserver.php/principals/test
does this resolve your problem?

**Comment by ygoe** [comment]
No. "Wrong URL".

**Comment by timoberger** [comment]
for me it looks like you made some mistakes within SabreDAV
the url http://unclassified.de/dav/calendarserver.php/principals
returns"Sabre\DAV\Exception\NotFound" - "Principal with name test not found"
which says that the user "test" exists but you did not setup any "principals" (something like "principals/test", "principals/admin/calendar-proxy-read" and "principals/admin/calendar-proxy-write") please check the sql-examples shipped with SabreDAV.

**Comment by ygoe** [comment]
I've done all the setup that's documented, so then there's a problem with SabreDAV. It's already a long time since I've done it and I don't really remember how it all worked. But it seems that DAV really is too complex to use. I've also read that elsewhere AFAIR. I think I'll just stay with the seemingly easier alternative Google calendar. They've got an API for building clients and it's already built into Android so there's not even anything to do and that end.

**Comment by timoberger** [comment]
if its fine for you i will close this issue.
feel free to reopen when needed.
