### ISSUE TITLE
TimeZone issue

### ISSUE THREAD

**Issue by wsat** [gggard/AndroidCaldavSyncAdapater#68]
I am synchronizing my business exchange account to my home server using DavMail. Calendar events show up there in the right time zone. However, when I then synchronize my home server with my mobile device (while being in a different time zone), on the mobile device the time is not correct - it shows the original time.

Example: 
Meeting scheduled at 15:00 UK (GMT). 
On my home server in Europe at 16:00 (CET). 
On my mobile in UK at 16:00 UK (GMT).

**Comment by timoberger** [comment]
will be fixed with the next release
