### ISSUE TITLE
Support for Tine2?

### ISSUE THREAD

**Issue by blurmonk** [gggard/AndroidCaldavSyncAdapater#72]
Hi

Can you pleasee add support for TIne2? It does not like Tine2`s caldav links for some reason. It says invalid server answer, check url. I put working caldav link in there naturally

thanks

**Comment by ghost** [comment]
for me it's working with tine. not the most up to date version

**Comment by marianolazzaro** [comment]
Working with Tine 2.0, I think it is October 2013 release.  I found other bugs, but it is not incompatible with Tine.

**Comment by timoberger** [comment]
i will close this issue.
feel free to reopen if needed.
