### ISSUE TITLE
Incorrect use of content-type text/plain for XML requests

### ISSUE THREAD

**Issue by hfyolle** [gggard/AndroidCaldavSyncAdapater#73]
App is sending CalDAV requests using text/plain content-type, when it should be application/xml (or at worse text/xml) as specified by RFC 4918 chapter 8.2

But using text/plain does not appear fully correct for XML payload

**Comment by timoberger** [comment]
should be fixed with 2324b89dee71949f77fba6fc387784ccab7c80a2
