### ISSUE TITLE
Incorrect support of /.well-known/caldav uri

### ISSUE THREAD

**Issue by hfyolle** [gggard/AndroidCaldavSyncAdapater#74]
Client sends:

PROPFIND /.well-known/caldav HTTP/1.1
Depth: 0
Content-Length: 143
Content-Type: text/plain; charset=UTF-8
Host: 10.13.2.123:5229
Connection: Keep-Alive
Authorization: ...

....

Server replies:

HTTP/1.1 307 Temporary Redirect
Location: /principals/u1@qa.com
Cache-Control: no-cache
Date: Thu, 11 Jul 2013 03:21:01 GMT
Server: Critical Path Calendar Server version 8.6.015
Content-Length: 0

Client sends:

GET /principals/u1@qa.com HTTP/1.1
Depth: 0
Host: 10.13.2.123:5229
Connection: Keep-Alive
Authorization: ...

Why GET /principals/u1@qa.com HTTP/1.1    ?
Should be PROPFIND /principals/u1@qa.com HTTP/1.1

**Comment by timoberger** [comment]
as far as i can see, there are no more GET requests.
please try my current developer version https://github.com/timoberger/AndroidCaldavSyncAdapater/releases/tag/V1.8-alpha-2
feel free to reopen when needed.
