### ISSUE TITLE
Cannot set calendar color in Google Calendar

### ISSUE THREAD

**Issue by olejnjak** [gggard/AndroidCaldavSyncAdapater#76]
Hi,

I'm syncing my work calendars, I don't know exactly which technology it uses, I guess iCloud.

But when I want to change the color in Google Calendar (built-in app in Android 4.2.2) the change color dialog very quickly disappears. I can spot the loading animation, but that's all.

I'm not sure if it doesn't have anything in common with issue 16 and I'm not even sure if it isn't bug in Google Calendar app.

I'm using Google Calendar v. 201305280 and CalDAV Sync Adapter v. 1.7.

**Comment by timoberger** [comment]
calendar created by the sync adapter are getting their color from the sync adapter. there is no way to change this color.
feel free to reopen when needed.

**Comment by draftii** [comment]
Hi,

Where can I change the colors in sync adapter (v1.8) ? 
If this is impossible,  it is provided in a future update ?

Think.

**Comment by timoberger** [comment]
@draftii the calendar server provides the calendar color to the sync adapter. there is no way to change this.

**Comment by alex-dot** [comment]
Researching on that, I do not see where it is specified that a caldav server pushes the color. There is nothing in the rfc's for caldav files (the only thing I could find was a proposed addition of a COLOR attribute for ical, but even those attributes should be propagated as a suggestion to the user) or the webdav protocol - as far as I can tell anyway.

So in which way is the adapter expecting a color assignment from the server? What is the interface? I am asking so something like that may be incorporated into radicale.

**Comment by timoberger** [comment]
Hi alex-dot,
You are right, the color attribute is not part of the regular rfc.
this is the request used by caldac sync adapter to identify a calendar and it's color.

```
<?xml version="1.0" encoding="UTF-8"?>
<d:propfind xmlns:d="DAV:" xmlns:c="urn:ietf:params:xml:ns:caldav" xmlns:cs="http://calendarserver.org/ns/" xmlns:ic="http://apple.com/ns/ical/">
   <d:prop>
      <d:displayname />
      <d:resourcetype />
      <ic:calendar-color />
      <cs:getctag />
   </d:prop>
</d:propfind>
```

if the attribute is unkown, the server will respond with a 404 (i think).

**Comment by olejnjak** [comment]
I'm just wondering what is the difference here, because when I connect to CalDAV server that our company uses using Macbook or iPad and its calendar app, the colour is always synced.

**Comment by timoberger** [comment]
@olejnjak i do not understand your request. can you describe it in more detail?
