### ISSUE TITLE
Cannot sync events created on Smartphone with Owncloud

### ISSUE THREAD

**Issue by 1uk4sh** [gggard/AndroidCaldavSyncAdapater#77]
Hi,

I can't sync / upload events from my mobile device.
The sync with my Owncloud CalDAV works and i can see new events created from web interface.

I'm also using Thunderbird / Lightning with the same Calender and the same settings. When I'm creating Events in Thunderbird they where synced with OC. So there is no problem with writing permissions.
Is there any Logfile or something else on my device for giving you more details?

I'm using Motorola Defy+ with Cyanogenmod 9 (Android 4.0.4)

Thanks @gggard for this app =)

**Comment by euphi** [comment]
+1
Sony Xperia Z, Android 4.2.2

**Comment by timoberger** [comment]
the current release syncs only one way
