### ISSUE TITLE
parse error from f-droid

### ISSUE THREAD

**Issue by HellTiger** [gggard/AndroidCaldavSyncAdapater#78]
Hello.

On my android device in the f-droid repo app i couldnt find CalDAV, will this mean my device isnt compatible?
i just downloaded the apk manually and launched it, then i had a parse error. 
unknown sources are allowed, and i downloaded the apk once via android www browser and once via esexplorer samba. both times parse error.

**Comment by timoberger** [comment]
this could be a reason why f-droid doesn't show you the app for installation:
you need at least Andoid 4.0 to be able using this sync adapter.

**Comment by HellTiger** [comment]
Yep, it was on android 2*
