### ISSUE TITLE
Does not push created event to radicale

### ISSUE THREAD

**Issue by rbu** [gggard/AndroidCaldavSyncAdapater#80]
I have set up a radicale 0.8 instance (with authentication) and synchronized AndroidCaldavSyncAdapater 1.7 against it. When syncing against a calendar with events, the events displayed correctly. However, when syncing against an empty calendar, new events will not be synced up. There is simply no attempt to PUT a new event in the server log. I have tried manually forcing a sync to no avail.

**Comment by timoberger** [comment]
the current release syncs only one way
