### ISSUE TITLE
Maybe stupid question, but is two way sync supported?

### ISSUE THREAD

**Issue by fancarpedia** [gggard/AndroidCaldavSyncAdapater#81]
Maybe it's stupid question. But when I create an Event on Samsung with Android 4.1, event is not stored on server, but server will not receive any request with new Event data.
So question is, support this sync adapter two way sync?

**Comment by EtienneM** [comment]
If you have a look [here](https://play.google.com/store/apps/details?id=org.gege.caldavsyncadapter) you can see in the News section that for now the synchronization is only from the server to the Android phone. The two way sync is a work in progress.

**Comment by fancarpedia** [comment]
O.K. I found it on GooglePlay. I was thinking that in current version it's working, because here in GitHut is written, that this feature was added (Creating .ics after Android Event) somethink like that ;-)
