### ISSUE TITLE
URL without trailing slash (/).

### ISSUE THREAD

**Issue by wilbertvolkers** [gggard/AndroidCaldavSyncAdapater#90]
With SOGo I am allowed to enter an URL without trailing slash (/). From server to Android everything works fine. In SyncAdapter.java, checkDirtyAndroidEvents() the url is formed to send updates to SOGo:

``` java
SyncID = caldavCalendarUri.getPath() + newGUID + ".ics";
```

This one then results in a non-existing calendar as newGUID is appended to the URL without a slash to separate them.

Workaround: ensure you register the URL with a trailing slash.

Fix: We could add something like:

``` java
if(mURL.endsWith("/")) {
  SyncID = caldavCalendarUri.getPath() + newGUID + ".ics";
}
else {
  SyncID = caldavCalendarUri.getPath() + "/" + newGUID + ".ics";
}
```

**Comment by timoberger** [comment]
are you in need of an updated release?
may i close this issue?

**Comment by wilbertvolkers** [comment]
Looks fine to me, close it if you like. I have the workaround until an update.

**Comment by timoberger** [comment]
thanks :)
