### ISSUE TITLE
Times of calendar entries not synced

### ISSUE THREAD

**Issue by lampi87** [gggard/AndroidCaldavSyncAdapater#91]
Hi!

If I sync my owncloud calendar with my phone (principals or calendars URL), the begin and end times are not synced.
Every entry is shown as full-time entry.

Greetings

**Comment by timoberger** [comment]
which version of caldav sync adapter are you using?

**Comment by lampi87** [comment]
The current one from play.google.com. I think it is 1.7 (29. March 2013)

**Comment by timoberger** [comment]
those is slightly outdated.
if possible try this one https://github.com/timoberger/AndroidCaldavSyncAdapater/releases/tag/V1.8-alpha-2

**Comment by lampi87** [comment]
Perfect, that solved the problem.
Thank you!!
