### ISSUE TITLE
Every request is doubled

### ISSUE THREAD

**Issue by fancarpedia** [gggard/AndroidCaldavSyncAdapater#92]
Hi,
In all version, I found this issue.
Every request is doubled.

"GET /caldav/calendars/stano/default/aced88ed-62ce-46b2-8bf0-5723e48c5b6f.ics HTTP/1.1" 401 292
"GET /caldav/calendars/stano/default/aced88ed-62ce-46b2-8bf0-5723e48c5b6f.ics HTTP/1.1" 200 1262
"GET /caldav/calendars/stano/default/ac9cd8d2-916e-4155-b477-1aed5749543a.ics HTTP/1.1" 401 292
"GET /caldav/calendars/stano/default/ac9cd8d2-916e-4155-b477-1aed5749543a.ics HTTP/1.1" 200 1389

In Lightning (thunderbird), iOS caldav implementation, authorization is requested only on first request, than all requestes are authorized by stored HTTP authorization.

Is it possible to optimize it?

**Comment by timoberger** [comment]
the org.apache.http.client.HttpClient sends new requests without any credentials at first and resends the same request with credentials without any notification.
this is not itended.

**Comment by fancarpedia** [comment]
Is it possible to optimyze, or this is not issue for CalDavSync?

**Comment by timoberger** [comment]
the httpClient sets its AuthState and AuthScope to null after a successful request.
i am saving the last AuthState and AuthScope to set them back into the httpClient before the next request is beeing executed.

the first request of a new sync will lead to a 401 status (as before) but every request coming after that will be preauthenticated.

fix will be released soon.

note: all request are using the same nonce count during a digest authentication

**Comment by timoberger** [comment]
will be available with the next release.

feel free to reopen if needed.
