### ISSUE TITLE
CaldavSyncAdapter has stopped working

### ISSUE THREAD

**Issue by justPoppingIn** [gggard/AndroidCaldavSyncAdapater#93]
Hello,

during sync with an owncloud server the message 'CaldavSyncAdapter has stopped working' appears. The events are only partially imported, most of the events are missing. With the next sync the order the events are synced seems to be the same, therefore most events are missing and can't be imported via multiple sync tries.
I sync via ssl with:
Android-Version 4.1.2
Owncloud Version: 5.0.10-1 (latest from OpenSuSE build service)
AndroidCaldavSyncAdapter (free): 1.7

Sync with the Thunderbird, Lighting and SOGo Connector package works well.

Kind regards

**Comment by timoberger** [comment]
the version V1.7 (currently available at googla play and f-droid) is very old.
if possible please try the following unofficial version
https://github.com/timoberger/AndroidCaldavSyncAdapater/releases/tag/V1.8-alpha-2

i am closing this issue. feel free to reopen it when needed.

**Comment by justPoppingIn** [comment]
V1.8-alpha-2 fixed the problem. Thank you very much :-)
