### ISSUE TITLE
Http error Error 405

### ISSUE THREAD

**Issue by obsdler** [gggard/AndroidCaldavSyncAdapater#94]
I'm trying to use it on a little bit awkward setup, there is Pound proxy -> Apache mod_rewrite -> Radicale as fastcgi

Works fine with Evolution & the contacts also work with the free CardDAV android app by some other guy. However in caldav-sync-adapter, I get "Invalid server answer, check URL"

The URL I gave is: http://rad.myname.mysite/myname/calendar.ics/

I also tried various variations. The adb logcat shows:

Force get calendars from 'http://rad.myname.mysite/myname/calendar.ics/' failed org.apache.http.client.ClientProtocolException: StatusCode: 405

However I tried on my computer

``` xml
lwp-request -H 'Depth: 1' -E -f -c application/xml -m PROPFIND http://rad.myname.mysite/myname/calendar.ics/
<?xml version="1.0" encoding="UTF-8"?>
<d:propfind xmlns:d="DAV:" xmlns:c="urn:ietf:params:xml:ns:caldav" xmlns:cs="http://calendarserver.org/ns/" xmlns:ic="http://apple.com/ns/ical/"><d:prop><d:displayname /><d:resourcetype /><ic:calendar-color /><cs:getctag /></d:prop></d:propfind>
```

(I believe this is what caldavsync ought to send)

and get correct answer

``` xml
207 Unknown
Connection: close
Date: Mon, 09 Sep 2013 14:52:42 GMT
Server: Apache/2.2.15 (CentOS)
Vary: Host
Content-Length: 1755
Content-Type: text/xml
Client-Date: Mon, 09 Sep 2013 14:52:43 GMT
Client-Peer: 95.143.172.208:80
Client-Response-Num: 1
DAV: 1, 2, 3, calendar-access, addressbook, extended-mkcol

<?xml version="1.0"?>
<D:multistatus xmlns:D="DAV:">
...
```

any idea how to debug this?

**Comment by timoberger** [comment]
did the error disappear?
