### ISSUE TITLE
Sync and content-type

### ISSUE THREAD

**Issue by AdamN1** [gggard/AndroidCaldavSyncAdapater#95]
Hello,
about the https://github.com/gggard/AndroidCaldavSyncAdapater/issues/34

**Comment by timoberger** [comment]
all PROPFIND requests are setting the following header
request.setHeader("Content-Type", "application/xml;charset=\"UTF-8\"");
see org.gege.caldavsyncadapter.caldav.CaldavFacade.createPropFindRequest(...)

to understand your problem better, i need a traffic dump of the questioned session.
can you please create a dump with Charles Proxy http://www.charlesproxy.com/
and send it to timoberger@users.sourceforge.net

**Comment by AdamN1** [comment]
i don't have this program, can i use wireshark or text version tshark ?

**Comment by timoberger** [comment]
wireshark would also be fine.
but keep an eye on what you capture and send to me

**Comment by timoberger** [comment]
i received your dump and i am able to see 2 PROPFIND request with 
Content-Type: text/plain; charset=UTF-8 (line 601 and 1210)
but i see also the Host-header that is not implemented in the current repository from gggard.
the Host-header is implemented in my fork of the Sync adapter, but there would also be a User-Agent.
whose repository are you using and what is the latest commit (534273ee95f19029b221fa63e1f1c4b6cb1ef567 or 0ee57d5d313f572dcfd66c2cba68c09a63ddf193)?

**Comment by AdamN1** [comment]
Repo https://github.com/gggard/AndroidCaldavSyncAdapater/tree/master/CalDAVSyncAdapter
commit f54e83280e

**Comment by timoberger** [comment]
can you please check the version within your device? (settings -> Apps -> CalDAV Sync Adapter)

**Comment by AdamN1** [comment]
I apologize for such a long delay.
After checking the version it turned out that the old is still there. 
Unfortunately, I had to uninstall the old version and install the new one, overwriting does not work.
thanks a lot.

**Comment by timoberger** [comment]
thanks for the report.
