### ISSUE TITLE
Color choice incorrect

### ISSUE THREAD

**Issue by michaesc** [gggard/AndroidCaldavSyncAdapater#97]
According to CalendarColors.java the first added calendar should get the color yellow, the next orange, then red, etcetera. When testing however, the colors set for the various calendars associated to the same user, passwd, and URL tuple don't follow the above index.

After setting the colors (the DAV property calendar-color) via iCal nothing is reflected in AndroidCaldavSyncAdapter even after clicking 'update' on the Android 4.3 calendar.

I just want the colors to be different for my four calendars, but right now they are almost the same (blue,purple,lightblue,blue.)

Version: 20130912 (git clone)
Android: 4.3 Build JSS15Q (Nexus 7 2013)

**Comment by timoberger** [comment]
i guess you cloned gggards master? could you please try my fork? i am currently not merging all my changes to gggards repo.

**Comment by michaesc** [comment]
It seems the timoberger fork corrects the problem with colors but is unusable in my case due to stability problems, namely CalDAV account entries disappearing from the list of entries associated with a user name, password, and host (only the URL endpath is different.) When adding new account entries in this way, sometimes (almost random?) previously existing account entries completely disappear.

Repeat: this stability problem is not in the branch.

I tried merging the color changes from the fork to the branch to work around the stability problems, but failed due to work time constraints.

**Comment by timoberger** [comment]
if i understand right:
- there are more than one calendar server on one host. i.e http://ww.example.com/caldav1/calendarserver.php and http://ww.example.com/caldav2/calendarserver.php
- all calendar server are using the same credentials.
  is this correct?

**Comment by michaesc** [comment]
Hello,

On Thurs., Sept. 12, 2013, timoberger wrote:

> if i understand right:
> - there are more than one calendar server on one host. i.e http://ww.example.com/caldav1/calendarserver.php and http://ww.example.com/caldav2/calendarserver.php
> - all calendar server are using the same credentials.
>   is this correct?
> 
> Hmm, I think you got the concept right but made a typing error.
> When making four entries with identical user/passwd and these URLs:

  https://calendar.hostname.tld/caldav.php/username/calname1/
  https://calendar.hostname.tld/caldav.php/username/calname2/
  https://calendar.hostname.tld/caldav.php/username/calname3/
  https://calendar.hostname.tld/caldav.php/username/calname4/

...they should obviously lead to four calendars in the CalDav Sync
Adapter. It works fine when using the gggard trunk. When using
the timoberger fork there is erratic behaviour. Always at least
one of the entries appears, sometimes two. Others disappear or
are replaced when switching screens, it's bizarre.

Still like the solution to the color problem though, to end
on a positive note.

**Comment by timoberger** [comment]
the sync adapter acts greedy during calendar update.
to be able to delete no more needed calendars, the complete list of calendars for the account have to be read. but this is done the wrong way.
i created a new issue #98

**Comment by timoberger** [comment]
this should be fixed now

**Comment by timoberger** [comment]
if needed feel free to reopen
