### ISSUE TITLE
Event is not eliminated after synchronization

### ISSUE THREAD

**Issue by FerbbIT** [gggard/AndroidCaldavSyncAdapater#99]
Hi Gerald,

Thank you for develop this app. In our case it's very useful.

We only have observed a problem:

A user create an event in the calendar application embedded in the Thunderbird or Zimbra Desktop applications. This event is viewed, in the Calendar app, in a smartphone LG Optimus L7 with Android 4.1.2 Jelly Bean operating system, running your app. The synchronization works properly.

But if the user who created the event decides to eliminate it, the user with the smartphone can´t see that the appointment is eliminated. In fact, he continues viewing the event although we do a manual synchronization.  Finally, the user with the smartphone have to eliminate this event manually. 

This problem occurs both with future events and past events.

Would it be possible for you to check this problem?

Thank you very much for your time.

Regards,

**Comment by timoberger** [comment]
the version 1.7 from google play or f-droid is some kind of old. please try one of my non official alpha-releases:
https://github.com/timoberger/AndroidCaldavSyncAdapater/releases

**Comment by FerbbIT** [comment]
Hi Gerald, 

We have tested the V 1.8 alpha version and the problem is solved. 

Thank you very much!!

How soon will you publish the 1.8 beta version in the Play Store?

Regards.

**Comment by gggard** [comment]
Thanks for the report, indeed you should thanks (and I too) timoberger who make a fatastic work on the project ;-)

**Comment by timoberger** [comment]
Hey Gerald,

Nice to read you. :)
What do you think about a new release 1.8?

**Comment by timoberger** [comment]
@FerbbIT I think i will stop the development for the release V1.8 and wait some days for new bug reports coming in from V1.8-alpha-3.

**Comment by FerbbIT** [comment]
Hi, 

We are trying with the v. 18 alpha 3 in some smarphones and we can tell you that this revision doesn´t work properly. I can´t see any event in the Calendar app of the smartphones. 

So, I have done an uninstall of the Alpha3 and then install again the Alpha 2 version. This version works properly. After synchronization, I see all the events on the Calendar app, or not, if I delete previously a specific event.

I hope this report can help you to improve the definitive 1.8 version.

**Comment by timoberger** [comment]
@FerbbIT are you adding new accounts with an url like http://www.example.com/calendarserver.php/calendars/username/calendarname (url with calendarname) then the issue #102 might apply to you.
if not please describe in more detail how many accounts are beeing created with their credentials and urls.
